# Normaliza páginas que no catálogo são armazenadas como fragmentos visuais.
# CTxx já fornece um documento HTML completo para a página canônica contato.html.
$ModeloId='CT05'
$ModeloNome='Contato Conversacional em Etapas'
$Payload='H4sIAKekmWoC/7VYzY7juBG+z1MwGgRtJ5bast1tt2Q7Oxk0kkM2WWSSAEGQAyVRNmckUktSbnsMP0WuuQQ5LLJATnmEfpM8SapIyb/dzmSBtAFZokkW66uvvir19EeZTM2mYmRpymL+ZopfpKBiMfMq4//8tx7JqKF+CpdCLqSv/VJmrJh573/Xv/Pm0yWj2XxaMkNJuqRKMzPzapP7E68ZFbRkM2/F2VMllfFIKoVhAmY98cwsZxlb8ZT59qHHBTecFr5OacFmIWxhuCnY/D2soUZOb93jm6k2G/z+yTaRa1/zz1wsokSqjCkfRnboRC+R2WZbUrXgIurHCU0/LZSsRRa9zcfwuYtTWUgVvQ3DMM7BgJ/Tkheb6J2CI/R+yYoVMzylPU2F9jVTPI/liqm8kE/+OlryLGNiF6Smf7ctufCXjC+WJgr7fb1axhnXVUE30ULxLMaLb1gJI4b5YLYuhY6CySBXJAzCSa52geYZ2x4fMrwLxyFtD5nneVzRLENH04KWVWc4qNa9+9VTb9Kv1t29wbxg6xgvfsYVSw2XInIW44+1Njzf+E0EIl1RQD5h5omhJ3gCoktaFFvD1sY3ChzPpSqjuqqYSqlmccGMAYxxJZ4Ezs7K9ogPKb1LBs0+y3CLmEb3/T5x5x1N2vPCwbu3wcOI/IJJiA4gbMFtQhXCPNIng/tq3exVbRsLlCV3CYOJa8eXaDQE3+OCC7aHPxjvgkrJhWJab09AWdAqgr0bO76RVTTqo5F2OuHbZpdR5TCMwlPe2L9wEjdUUzTjtY4eHmB6S409MQ67BlKcRDZ7yIf3dBfg9O0LQR0DSA+D46BaFtGCL8Q+eClcGPLGsGrvp5CCxVTwktq42ykkGN5pwiB6bnJAgRQrtl+TFDL9tAvYhiUKzmMzATKKReEQ3GqQH4/H8ZeTYsRKZ4ssB+c0GEJce3fg4f0IaRC+QoKhJcFwZOPVhnt8b+OVLiVIxiG6V3IsxAzLlY19ODgs3roIRiGY0bLgGXmbjeFzEe+zUCM593k4gA0dKjY0UcFyE6e10oBYJTmCHx/BOUZS4eOTI9mk348tnNwGKxjo9nQEoBSnAWoDMQkn4TiJz6J0vO0Itj2i+P3B6WiJJN0eQmjvEK8/dvwh8q1xthXGBD/AU86K7BxuBPQ0OvcTGx03m3BR1abXPiFKVDHa4t6P92ptjCyP45AkyXEQ7BkrWCvMHng0TAat3w4GDIysDWqBTYPdheljkba6AdmJSwET1PliZzNDijPZuKqae2IdQz4cvIRLszlJavBYXACx15KHI4bZNBj0XyDOKc12gQAvr5ePXYA/n8xhY/iEuyADvE7DC3fgJId80pEG+IxztCETg30a39DVBlR7f+rNXf/H8av7OgWLL5XxKKwDCOvuq09skytoI0DGcMk2V7LcSpQbs4maJDonNAalu9t9VbKM084hGhOEs7t1dftV0Wjq8RFlhoMT7Xl9ZWuyUixnSvuKZXXKMmibbJq7RziAFe6DVjvONup0JAt2fPdmeutanumta7iwuYEGi3KBuqr1zEOHPGiNqK2ZzSDeQxeV8dV8akt720qRRc1pBh2VG50uQ/sLSM/zv4gkgoGT+vlvissATIbzaTX/fUkJW4Po8+fvRcrhoSTQ4FVUE3TqMyyrmJZkxXVNC5JJgjGpC7sLYYR+rDNKKAG5B7c/UwX3kFSQfpqSjGk4tQTZeP5nao1W4Ks9N1xad9qaCi7xdkwKeLrlMPLSl9vi1oKCfaPriNq1WIERsyMTtmy5Etm0vjgy8/pgBWW5ndfUS2/+iBCQEDwgI4ATpgCag/kHmSh06NuakZVMn7/HO7V3WP0MYB2cONdQC+w4iTgdbw9TJx/Bh5n3jZIfmZHe/NdyBcC7J3vC+QfIrx4OZbWRPcD7+TtIHgFBlzUOVxJSOmjPeuusfZnVDzU28UCp5sYZfFcsIMBrrlEgoV+DvpPbmBJIDvH83fPf5Q8z9w1VKfCNevP2zhl8LwsKSkPt1j3kGRI2kwo9ZCv09YcZ/E1tFGBqvwjMq0ULKrJ/z1YwaCmrgfvwZsQWEo6mL0027MPrBclO2BVeZ9fgnF3vZQlBhxexUmqS04Iis0pHtEtmuUqISYNFmfDMqYWPr2YesZq8lAXoNgSY1UTIkl1OZiA2hUfwXRHO5x4uljLf/vBC6jbl74LdKP/e/A+ygCrzWqywuHlWn7ioj6d9Mb6D6/gOz/F91KliK0pqiDqkjqYLEDuouTZvXkO37TQOmJVIkcU5xlZo1zY1gXagNKiO34JmWoXIQFOLJSO8xAyjMDVAPNvN/y/QPooV/1JcCXYLJ+AOz8C1DYI3//df/9IiegX60Tn0X7dwg4xA30ezFvIKomIoef6Hqxs5V6UTACw19p8SMiCPJcSslUOoS/Amj5MhuUGMXLkiORdQn6iE1MUbsM/Af9gGqlNVQCvYKlb1P8D8mHGAeU+WV7C8bQoQDGDtBmRSxSszfwNn1IYgnnr2pyCAliytUbMD5MTmAytgnVTviqJzYzuHm+6fewlV/33y4TUUluCrGtIYu+lZv9fK3s1NnNfCVcaF7Ijutp3zNTXLAJqnTr/nbrnoDHui243tUQMQwkeaLjsd3ePd2VwHFpNfQSUIjFwsCta5cbX0psdns1mzLSzHsx9WJ3Z18sJqKWDl9LBwd81Xp+k33f3GCW4qRQpB/TTrgIlt63ISIIE1M0EzEoPjYXcH79xXDGC2XNse9mhO+tOwe30rZM2XbeXjVkgdRxVglu39bu0/7P4DonxVI8ATAAA='
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Backup([string]$r){$p=Full $r;if(!(Test-Path -LiteralPath $p)){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};Backup $r};[IO.File]::WriteAllText($p,$c,$Utf8)}
if($env:CATALOGO_S_CONTACT_EMAIL){$e=$env:CATALOGO_S_CONTACT_EMAIL.Trim();if($e){$ConteudoModelo=[Text.RegularExpressions.Regex]::Replace($ConteudoModelo,'[A-Za-z]+@empresa\.com',[Text.RegularExpressions.MatchEvaluator]{param($m)$e})}}
if($env:CATALOGO_S_CONTACT_ENDPOINT){$e=$env:CATALOGO_S_CONTACT_ENDPOINT.Trim();if($e){$s=[System.Net.WebUtility]::HtmlEncode($e);$ConteudoModelo=$ConteudoModelo.Replace('data-contact-endpoint=""','data-contact-endpoint="'+$s+'"')}}
if($env:CATALOGO_S_WHATSAPP){$ConteudoModelo=$ConteudoModelo.Replace('https://wa.me/5500000000000',$env:CATALOGO_S_WHATSAPP.Trim())}
if($env:CATALOGO_S_INSTAGRAM){$ConteudoModelo=$ConteudoModelo.Replace('https://instagram.com/',$env:CATALOGO_S_INSTAGRAM.Trim())}
if($env:CATALOGO_S_FACEBOOK){$ConteudoModelo=$ConteudoModelo.Replace('https://facebook.com/',$env:CATALOGO_S_FACEBOOK.Trim())}
Put 'contato.html' $ConteudoModelo
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado em contato.html."
Write-Host '[Catálogo S] CTxx substitui somente contato.html e cria backup quando necessário.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
