from pathlib import Path
import shutil, html, re
R=Path('.')
keep={'A01-Glassmorphism-Vidro-Fosco','A02-Vidro-Escuro','A03-Vidro-Liquido','A06-Efeito-Acrilico','A91-Mesh-Gradient','A92-Gradiente-Animado','A93-Aurora-Gradient','A94-Fundo-com-Glow-Radial','A95-Orbes-de-Gradiente-em-Movimento','A96-Gradient-Noise','A99-Film-Grain-Noise','A104-Grid-Background','A127-Starfield-3D','A145-Icone-Linear-1D','A146-Icone-2D','A147-Icone-3D','A13-Sombras-em-Camadas','A14-Sombra-Ambiente','A16-Sombra-Colorida','A18-Drop-Shadow-por-Forma','A11-Elevacao-no-Hover','A12-Elevacao-Suave'}
for p in (R/'efeitos').iterdir():
    if p.is_dir() and p.name not in keep: shutil.rmtree(p)
BASE='''*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Arial,Helvetica,sans-serif;background:#000;color:#f7f3e9}.demo-screen{min-height:100vh;background:#000;display:grid;place-items:center;position:relative;overflow:hidden;padding:68px 24px}.demo-meta{position:absolute;left:24px;top:20px;color:#c8c8cb;font-size:12px;letter-spacing:.08em;z-index:20}.demo-meta b{color:#fff;margin-right:8px}.demo-family{position:absolute;right:24px;top:20px;color:#666a70;font-size:11px}.demo-hint{position:absolute;left:50%;bottom:20px;transform:translateX(-50%);color:#777b82;font-size:11px}.demo-shell{width:min(1120px,94vw);min-height:min(700px,78vh);display:grid;place-items:center}.code-section{min-height:100vh;background:#08090c;padding:56px max(20px,5vw) 72px}.code-wrap{max-width:1180px;margin:auto}.back{display:inline-block;margin-bottom:28px;color:#d1ad73;text-decoration:none;font-size:12px}.code-head{display:flex;gap:18px;align-items:flex-end;justify-content:space-between;margin-bottom:18px;flex-wrap:wrap}.code-head h1{margin:0;font:500 clamp(34px,5vw,64px) Georgia,serif}.code-head p{margin:8px 0 0;color:#aaa69e;line-height:1.65;max-width:760px}.copy{border:1px solid #ffffff24;background:#111318;color:#f7f3e9;border-radius:9px;padding:10px 14px;font-weight:700;cursor:pointer}pre{margin:0;background:#111318;border:1px solid #ffffff18;border-radius:14px;padding:22px;overflow:auto;max-height:68vh;color:#d7d9dd;font:12px/1.65 Consolas,monospace;white-space:pre}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}'''
def slug(s):
    t=s.translate(str.maketrans('áàãâéêíóôõúçÍÁÀÃÂÉÊÓÔÕÚÇ','aaaaeeiooouciAAAAEEOOOUC'))
    return re.sub(r'[^A-Za-z0-9]+','-',t).strip('-').replace('icone','Icone')
def page(id,name,fam,desc,body,css):
    block=f'<style>\n{css}\n</style>\n{body}'
    d=R/'efeitos'/f'{id}-{slug(name)}'; d.mkdir(parents=True,exist_ok=True)
    for fn in ('bloco-pronto.html','bloco-pronto.txt'): (d/fn).write_text(block,encoding='utf-8')
    hint='Passe o mouse sobre os cards.' if fam=='Elevação no hover' else ('Compare a sombra nos três objetos.' if fam=='Sombras' else 'Compare a aparência dos ícones.')
    out=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{id} — {html.escape(name)}</title><style>{BASE}</style></head><body><section class="demo-screen"><div class="demo-meta"><b>{id}</b>{html.escape(name)}</div><div class="demo-family">{fam}</div><div class="demo-shell">{body}</div><div class="demo-hint">{hint}</div></section><section class="code-section"><div class="code-wrap"><a class="back" href="../../index.html">← Voltar ao Catálogo S</a><div class="code-head"><div><h1>{id} — {html.escape(name)}</h1><p>{html.escape(desc)} Situação: candidato.</p></div><button class="copy" id="copy">Copiar código</button></div><pre><code id="source">{html.escape(block)}</code></pre></div></section><script>const s=document.getElementById('source').textContent;document.getElementById('copy').onclick=async e=>{{await navigator.clipboard.writeText(s);e.currentTarget.textContent='Copiado';setTimeout(()=>e.currentTarget.textContent='Copiar código',1200)}};</script></body></html>'''
    (d/'index.html').write_text(out,encoding='utf-8')
shadow_common='''#{id}{width:min(1000px,94vw);height:min(620px,72vh);border-radius:34px;background:#25272c;display:grid;grid-template-columns:repeat(3,1fr);gap:34px;align-items:center;padding:clamp(30px,5vw,70px)}#{id} .card{height:260px;border-radius:28px;background:#f4f5f6;color:#15171a;display:flex;flex-direction:column;justify-content:flex-end;padding:26px}#{id} .card b{font:500 28px Georgia,serif}#{id} .card span{font-size:11px;color:#666;margin-top:8px}'''
def shbody(id): return f'<div id="efeito-{id.lower()}"><article class="card"><b>01</b><span>mesmo objeto</span></article><article class="card"><b>02</b><span>mesmo objeto</span></article><article class="card"><b>03</b><span>mesmo objeto</span></article></div>'
def shcss(id,extra): return shadow_common.replace('{id}',f'efeito-{id.lower()}')+extra
page('A13','Sombras em Camadas','Sombras','Várias sombras juntas criam profundidade mais natural.',shbody('A13'),shcss('A13','#efeito-a13 .card{box-shadow:0 2px 3px #0002,0 12px 22px #0003,0 38px 70px #0005}'))
page('A14','Sombra Ambiente','Sombras','Sombra ampla e macia, quase sem direção.',shbody('A14'),shcss('A14','#efeito-a14 .card{box-shadow:0 26px 70px rgba(0,0,0,.34)}'))
page('A16','Sombra Colorida','Sombras','A sombra recebe a cor de destaque do próprio objeto.',shbody('A16'),shcss('A16','#efeito-a16 .card:nth-child(1){background:#dcedff;box-shadow:0 28px 58px #3e9cff66}#efeito-a16 .card:nth-child(2){background:#eadfff;box-shadow:0 28px 58px #9658ff66}#efeito-a16 .card:nth-child(3){background:#ffe0ee;box-shadow:0 28px 58px #ff5b9d66}'))
page('A18','Drop Shadow por Forma','Sombras','A sombra acompanha a forma real do objeto.',shbody('A18'),shcss('A18','#efeito-a18 .card{background:transparent;display:grid;place-items:center;padding:0;box-shadow:none}#efeito-a18 .card:before{content:"◆";font-size:150px;color:#f4f5f6;filter:drop-shadow(18px 28px 20px #0009)}#efeito-a18 .card>*{display:none}'))
lift='''#{id}{width:min(1000px,94vw);height:min(620px,72vh);border-radius:34px;background:#17191e;display:grid;grid-template-columns:repeat(3,1fr);gap:28px;align-items:center;padding:clamp(30px,5vw,70px)}#{id} .card{height:280px;border-radius:28px;background:linear-gradient(145deg,#20242c,#111318);border:1px solid #ffffff18;color:#fff;display:flex;flex-direction:column;justify-content:flex-end;padding:28px;box-shadow:0 10px 24px #0005}#{id} b{font:500 28px Georgia,serif}#{id} span{font-size:11px;color:#9da0a6;margin-top:8px}'''
def lbody(id): return f'<div id="efeito-{id.lower()}"><article class="card"><b>Passe o mouse</b><span>card 01</span></article><article class="card"><b>Passe o mouse</b><span>card 02</span></article><article class="card"><b>Passe o mouse</b><span>card 03</span></article></div>'
page('A11','Elevação no Hover','Elevação no hover','Elevação rápida e perceptível para cards clicáveis.',lbody('A11'),lift.replace('{id}','efeito-a11')+'#efeito-a11 .card{transition:transform .28s ease,box-shadow .28s ease}#efeito-a11 .card:hover{transform:translateY(-14px) scale(1.015);box-shadow:0 32px 65px #000a}')
page('A12','Elevação Suave','Elevação no hover','Elevação pequena, lenta e elegante.',lbody('A12'),lift.replace('{id}','efeito-a12')+'#efeito-a12 .card{transition:transform 1s cubic-bezier(.16,1,.3,1),box-shadow 1s cubic-bezier(.16,1,.3,1)}#efeito-a12 .card:hover{transform:translateY(-6px) scale(1.003);box-shadow:0 26px 58px #0008}')
SVG='<svg viewBox="0 0 24 24"><path d="M12 2 4.5 5v6c0 5 3.1 9.2 7.5 11 4.4-1.8 7.5-6 7.5-11V5L12 2Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg>'
icon='''#{id}{width:min(950px,94vw);height:min(600px,72vh);border-radius:34px;background:#0b0c0f;display:flex;align-items:center;justify-content:center;gap:clamp(26px,5vw,78px);padding:40px;perspective:900px}#{id} .tile{width:clamp(150px,20vw,220px);aspect-ratio:1;border-radius:34px;display:grid;place-items:center}#{id} svg{width:55%;height:55%;fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round}'''
def ibody(id): return f'<div id="efeito-{id.lower()}"><div class="tile">{SVG}</div><div class="tile">{SVG}</div><div class="tile">{SVG}</div></div>'
page('A145','Ícone Linear (1D)','Ícones','Traço puro, sem volume.',ibody('A145'),icon.replace('{id}','efeito-a145')+'#efeito-a145 .tile{background:#111318;border:1px solid #ffffff16;color:#e7e8ea}#efeito-a145 svg{stroke-width:1.35}')
page('A146','Ícone 2D','Ícones','Cor e sombra curta dão leitura sem volume real.',ibody('A146'),icon.replace('{id}','efeito-a146')+'#efeito-a146 .tile{background:linear-gradient(145deg,#1f2634,#11141b);border:1px solid #ffffff14;color:#83d8ff;box-shadow:0 16px 34px #0008}#efeito-a146 svg{stroke-width:2.1;filter:drop-shadow(6px 8px 0 #2f4f8a66)}')
page('A147','Ícone 3D','Ícones','Volume, luz e sombra criam aparência tridimensional.',ibody('A147'),icon.replace('{id}','efeito-a147')+'#efeito-a147 .tile{background:linear-gradient(145deg,#303744,#0c0e12);border:1px solid #ffffff1d;color:#eaf6ff;box-shadow:inset 12px 12px 22px #ffffff0a,inset -14px -16px 28px #0008,0 32px 58px #000b;transform:rotateX(12deg) rotateY(-13deg)}#efeito-a147 .tile:nth-child(2){transform:translateZ(50px)}#efeito-a147 .tile:nth-child(3){transform:rotateX(12deg) rotateY(13deg)}#efeito-a147 svg{stroke-width:2.2;filter:drop-shadow(7px 9px 0 #7fcfff24) drop-shadow(0 14px 16px #0009)}')
(R/'README.md').write_text('''# Catálogo S\n\nBiblioteca pessoal de componentes e efeitos reutilizáveis.\n\n## Efeitos ativos\n\nA biblioteca de efeitos foi reduzida para 22 candidatos, divididos somente em: Fundos e telas, Ícones, Sombras e Elevação no hover.\n\nO objetivo é qualidade e utilidade, não quantidade. Os efeitos removidos permanecem recuperáveis pelo histórico Git, mas não fazem parte da biblioteca ativa.\n\nCada efeito ativo possui `index.html`, `bloco-pronto.html` e `bloco-pronto.txt`.\n''',encoding='utf-8')
(R/'documentacao'/'PADRAO-VISUAL-DOS-EFEITOS.md').write_text('''# Padrão das demonstrações de efeitos\n\nA demonstração deve usar o contexto real do efeito. Fundos ocupam uma seção inteira; vidro é aplicado à superfície de fundo de um painel; ícones são mostrados como ícones; sombras usam objetos neutros; elevação só acontece no hover.\n\nA área externa das demonstrações usa preto. Uma superfície auxiliar pode ser usada apenas quando necessária para enxergar sombra ou relevo.\n\nFamílias ativas: Fundos e telas, Ícones, Sombras e Elevação no hover.\n\nNão adicionar efeitos apenas para aumentar a quantidade.\n''',encoding='utf-8')
print('focused effects ready')