$ModeloId='F02'
$ModeloNome='Rodapé Editorial em Faixas'
$Payload='H4sIAAKKmWoC/51XS2/bRhC+51cs5ItdmBJJPWyTspBX0/SQNkiC3pfkUNqY3CV2l7IcQUBPvbfoHyh6CFKgvRRFgR6jf5Jf0tmlJFMPuk59ILyvmW+++WZ2NUyF0CAJSy5bMdU0E2PhpK7fIgmOnM2UcnKRQHbZeoZrowdDpW8yGD04qp+ZOw7jV8GRh39uGjpOLIHmwVHqQZSYcUELkDiO0jMwYwlJcHQBfur3w1Rw7aQ0Z9lN8Egymp0+h2wKmsX0VFGuHAWSpWEsMiGDKZXH1tlJGNH4aixFyZPVrHVystiGRr6YR2LmKPaO8XEQCZmAdHBmsb2Lziv7jE/Qmw41zLSTQCwk1UzwgAsOu5bb+HFwu5gnTBUZvQnGkiWh+TgacpzR4KDZMucq8Np+P5WkfYbfMGccD7LxRAdd1y1m4QqXFkXgFTOiRMYSsqLT74Ub2FqLfH/HQWBKo/scuJ4XNElM8P1zPBhnNC+O/UExOx1Mr08v/GJ2gEqbv5NwHVeawSw0HydhEmLLSBVY+LZUmqU3GCfX6CxQBY3BiUBfA/CDwK5YfAVybtOOaYHAMwzY4XXFyYXrhhloVKdjzBnsbe8c8iorWqIoUiHzoCww4TFVcDcBZOLPczpzrlmiJ8HZwLjLqRwzHviGEpe41n3Qd90VPz1/xc85EnXSaV/45CsQeAQladW4A89pu/0+5AdxcLhWjTnoo48zdycH6zqqJHmUnmEdnf+fZNhdwJNGXGTSna+oQBbIxSoRlgkfRx1vO+5Fk52ibsbvoZ0V+CiOBhTCWra7uJgxDusK8NqDg/hMiudbQTeWQcXQeRyuaF5vQbIXDZYJ40Wp56YSK124ltPAW3nBcS0jVnMFlUjqJitpGopSm0hsd1j7DqykKho9JILYntYYIYlKhMrnn+E1LqXC/wvBMMvyPyvH/ezKMR3sfj2tiy1NQgFUH3dPvVSehGNaBD1TYWs6eoN7d53DDdxCihB6sqNWz6/LtevfT66VpaLWEbp+PFk3BHdN9KDfT/uDum79fd32D2JFC2TS20LaW3e424a31+AGd6WpwQ3dpCnKRHy1IX1gNbgKped30+7FTgk2WgwmYortuX7d4m190tBiJSu2a5RmbMwdhlpRQQxWoHdeEVYwfl0w3v2vKQOsVhnn+LaoRYkNohk14XS6jdwAMb6r3notcWg+iwcPc0gYPb4VzLnBezJveg00FEsqm7rnvPYe8Pvu4eTYomw0TRrMW7VXx6rdgddxvMWBoPqNQd3t+X5eaanFolFBddFY9vHulvrwJYfYh53VI3SYsKmRilKXrTX9+EYlZKiqM/XFzXugNRqiBLfWqjdJa/QtSRmnGdE0j5YfchKLvOT4EEWPeGI0nPijZ8C0INiVKTGCZrykktj/sWwUbQ87uAn3VwCawJi0I45Jd/SN0FThm5tgvzCOcGpYjF5BDBElXExZQhNQp2TClF7+iXeJIkAyypfvqQlG4FlkSNsB4AGioCTg5JRliKUYDe0tU3Ntxuja3n9E3xRw2QKzu0UoWncyGpnX/uuNlRbBnMcwERleUJctNP/Q7m8jOWinur9WhqpBa/RIKeRRkk8//DTsVJPIifFcp2bYwfztZ9HopjGLVloVc69LSl4Y0j7+sabtKShU0ikppEhQccgUzLCFsuVvPDbMYZZQceXy98QOzCsAW9Ly/fJX0SaPIRPkuZDsnWlU5OPf5LGkak3jVkaxedRBoTINpJ7xH5cIEfH0RkNKJhLSy9ZRa/SCcpaC0mLYoVsLL6V4C5jF3fknIgPE9RfsrTxly18kqwx1EMidgJ5UsoQ9QLiA9bAPB/kEI7Ldha/zAt8hiu7NI6F0LGl+PzxfKgUmFdkeoDcg830aXko2xQvS1MA+Q+KK7dPzKAYUX8Sy20MVqga12Q60agmjjx+I7/oDspEW+fT9z7bOYflPYvTEEqwza9qITMOYJUK11/3BONqC/8Z5/GoX4QtaUILGFDa83bXvRKZNPxEEfwsKrJ8fbyNYB9CpfrmP/gWV026rwg8AAA=='
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force};[IO.File]::WriteAllText($p,$c,$Utf8)}
function Slots([string]$h){$m="<!-- CATALOGO-S:SLOT:MENU:START -->`r`n<!-- CATALOGO-S:SLOT:MENU:END -->";$c="<!-- CATALOGO-S:SLOT:COMPONENTES:START -->`r`n<!-- CATALOGO-S:SLOT:COMPONENTES:END -->";$f="<!-- CATALOGO-S:SLOT:RODAPE:START -->`r`n<!-- CATALOGO-S:SLOT:RODAPE:END -->";if($h-notmatch'CATALOGO-S:SLOT:MENU:START'){$h=$h-replace'(?i)<body([^>]*)>',('<body$1>'+"`r`n"+$m)};if($h-notmatch'CATALOGO-S:SLOT:COMPONENTES:START'){$h=$h-replace'(?i)</body>',($c+"`r`n</body>")};if($h-notmatch'CATALOGO-S:SLOT:RODAPE:START'){$h=$h-replace'(?i)</body>',($f+"`r`n</body>")};$h}
function SetSlot([string]$h,[string]$n,[string]$c){$e=[Text.RegularExpressions.Regex]::Escape($n);[Text.RegularExpressions.Regex]::Replace($h,'(?s)<!-- CATALOGO-S:SLOT:'+$e+':START -->.*?<!-- CATALOGO-S:SLOT:'+$e+':END -->',"<!-- CATALOGO-S:SLOT:$n`:START -->`r`n$c`r`n<!-- CATALOGO-S:SLOT:$n`:END -->")}
$p=Full 'index.html';if(!(Test-Path -LiteralPath $p)){Put 'index.html' (Slots '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Projeto</title></head><body></body></html>')};$h=Slots ([IO.File]::ReadAllText($p));Put 'components/catalogo-s/rodape/ativo.html' $ConteudoModelo;Put 'index.html' (SetSlot $h 'RODAPE' $ConteudoModelo)
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado como rodapé ativo."
Write-Host '[Catálogo S] Fxx é singleton: outro Fxx substitui somente o rodapé.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
