$ModeloId='F04'
$ModeloNome='Rodapé em Vidro com Glow'
$Payload='H4sIAAKKmWoC/41YzXLjuBG+z1Og5JoqOyVKICnaFCmrsrXZn1y2ptabqlxBoikhQxIMANryqnTNA+QVctia3FO5r98kT5IGSf2QljyemrFJgGh8/fXX3cAsMikNKCL4/ShlhuVyJZ2MzkaE45tzGNJOITnk96PvcW75YaHNcw7LD1ena7aV1MIIWUYKcmbEI8RCS/uEQ+0TxPIRVJbLp2gtOIcyTlj6eaVkXfLoigZ0Tnmcylyq6AqybJ4lcSZL42SsEPlz9I0SLB//CPkjGJGysWaldjQokcUV41yUq+j2ttqQNGdFde2G1WY8e3waB7Nqc7PrgyV/2CZy42jxq12VSMVBOTiy63/Fti0aUa5xGxMb2BiHQypV61YpSxhYjhLIpIJxf5BlSDMaKw2UJhqN4gNZLEFqaqTmV0eUHDaR48UdHsW4qHUU0I9xJnI0ECV5ra4DdOwmlhVLhXmOJiHaEmhXOfCIxvUboLZPgpt15N/SahOvQazWJvJC+5JDZqK7j7GRVeTifqdxcUMepswPYlaKovUbTToYRmYcRuaaANOA6B1ZGyLKTJTCAGEWcYlBH2JpuWihzLwTKD61L6p5DhGDNEYWkd9Hk1Hm+cwLz6JJiOt+Hc4fP8NzplgBmpw4sjVyaxRKCpkqoubJStbn10GASrJAx/SG6JTlcO1O3OBmtztrKblsyZlZU44bnNqazD00NdDnxNrTa8jzM3nVcleI8tr1LGdjl9KPN3HB1EqgomojOwlFLqYD6ktwcpU1f7xkoC7fcn5CcC5KYMpZ2WmU07U7oxxW4265G+yfaEhmwcfDW3oTNwm1Zhyzm5IZmiWuBUeuKKXzsSg1GEKJRdQt8mmzMVeyck4F7nkocKKZqTHNkGvfOuc8QfJZILvvXjGoNZcZ3mfHm+nZ4I/om1R5Paq8cRP6iimcJAip935HG/K4F3LKbt6Rwy3ggonyjCK40FXOnqOVEjy2PxwDRWVV52AFq4tSR+7ECzJFFFTAzLU/ntzh6028YhVmIWpgX0JtuTy7dYLoOVl7205n1EYTP25qNFapNuhTl/wAEj/A+tyU5hyMdUzbeoXmnQn1Ayh2Fzeo0P7G6SqVn67jk+08LO/7BsGSlKZB2yCwjkPkWi9sTJyunriTu/NBrxOdKpHAdk9blsMmPtm2KZAXUygYpNB8Pu/n0BX1XeoGt7dHUi9weoCChaqqzRZzusNAYwsqcvcweso7EdKeDgQWY8Gz/jfqOWztNpmI3Oze3D+psdqWh7J8rMrN8xHEq9Z06jcPEQbbQ6LMp14Wp7XS+Nop/DRg4QVWcD1Z+3ud+YgflRYcQ8+zLMx6oW97WE9oWKGhaDv2sRjXVQUqxf6wu7AtO2giyWX6+XiwsCD2+8+TxEvCgfQuWozWthJ1J4mruyybQXg+wZqG90Z2NzJluViVDra0QkcpNJT+rdZGZM/OvoBZCsBJwDwBnrFshjdtdu+LrZbEpvk+mk3XH8rcDfuS9iijmX+75yDkzGPhIAbnNS5TPLf1c81istE/+QCp77LvRHzNc6+44RP61nP/YqIOT1LuoNftm9f8IKwQALLWqacWwZzSEyfnl3w02Hv09muB6rvdrCGic/vu6PXdMTQXEu3Ohzmy32u5bTUm3Rwecwrggl0fy1poVXCzHZzaO1H4dq01sLvUdS60Fewp+O8gLt9miheet9NU+NZQuz5yp467eyMX9pKle6tn/ArO+PUe3O9DaI9TbyA8jbINuw2rMk3xdrhQkDap3No6gq8UZKC0o4DXKXC8XnUZb18Hrrx1ozgegpsTw+7DYtrdzRZcPNqbkNb3o8NJB+9uhAxnLEnNBE7pFu/pdMPIaLlYe8ufIKlzRh6etXV3McWhRbX8S0GU5Kx6+UI4kEeBpzOSSZ1KksqCCHRclOzlt5d/ScJMIXX28kXh9Y1g/8IfuBQJ1oSLlTBM6DFpCKwrPMcT2GC5Fi//LrFAaDSta/yC2LsoHuX1ZDGtlgtb13uO7lsaYm6aKjHPFdyPAP3MR4ThJdLJWWJvsw9QE3Da8aaurGWOpu9HP0MKCSOlRG8YB42m2v7Y2Wpf+sa+0Rr9VKPl//7xz8W0/WK5mFp4+KsjtqO5ZL0IoDoswf7yU8sGMusvF4ysUSX3o6vR8hNKl1lLbDFlvRlEaturHo7/GesNHkyR9v/Aq8mfJeMFq5rhKWL5CqrvCpSrZq9QPchEwdD2d3+vRfVq9FumFAjFXkH5Fksrsx6/D8rR3QGWP8n0te01K1eAGTOceIAVXhTKl99e0fnQ1OQemsUU8+Vc3rQFAHENM62xYdWHRvAfduNy+YvkKHL8q4VNHlSzRGnjSUWWKGnUh/2o3apd8PsX4lHvlvRzjvz+X/JJiUdcaIVpX38BVciDhSGWprWO+tL4aej1Dz8OR/7aUtDAaf0//Gr/y2j5f5ec5Q47EgAA'
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force};[IO.File]::WriteAllText($p,$c,$Utf8)}
function Slots([string]$h){$m="<!-- CATALOGO-S:SLOT:MENU:START -->`r`n<!-- CATALOGO-S:SLOT:MENU:END -->";$c="<!-- CATALOGO-S:SLOT:COMPONENTES:START -->`r`n<!-- CATALOGO-S:SLOT:COMPONENTES:END -->";$f="<!-- CATALOGO-S:SLOT:RODAPE:START -->`r`n<!-- CATALOGO-S:SLOT:RODAPE:END -->";if($h-notmatch'CATALOGO-S:SLOT:MENU:START'){$h=$h-replace'(?i)<body([^>]*)>',('<body$1>'+"`r`n"+$m)};if($h-notmatch'CATALOGO-S:SLOT:COMPONENTES:START'){$h=$h-replace'(?i)</body>',($c+"`r`n</body>")};if($h-notmatch'CATALOGO-S:SLOT:RODAPE:START'){$h=$h-replace'(?i)</body>',($f+"`r`n</body>")};$h}
function SetSlot([string]$h,[string]$n,[string]$c){$e=[Text.RegularExpressions.Regex]::Escape($n);[Text.RegularExpressions.Regex]::Replace($h,'(?s)<!-- CATALOGO-S:SLOT:'+$e+':START -->.*?<!-- CATALOGO-S:SLOT:'+$e+':END -->',"<!-- CATALOGO-S:SLOT:$n`:START -->`r`n$c`r`n<!-- CATALOGO-S:SLOT:$n`:END -->")}
$p=Full 'index.html';if(!(Test-Path -LiteralPath $p)){Put 'index.html' (Slots '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Projeto</title></head><body></body></html>')};$h=Slots ([IO.File]::ReadAllText($p));Put 'components/catalogo-s/rodape/ativo.html' $ConteudoModelo;Put 'index.html' (SetSlot $h 'RODAPE' $ConteudoModelo)
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado como rodapé ativo."
Write-Host '[Catálogo S] Fxx é singleton: outro Fxx substitui somente o rodapé.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
