# Normaliza páginas que no catálogo são armazenadas como fragmentos visuais.
# CTxx já fornece um documento HTML completo para a página canônica contato.html.
$ModeloId='CT02'
$ModeloNome='Contato Social em Vidro'
$Payload='H4sIADCqmWoC/81Y247byBF991f0cjDAjCFSJEVKFDUa2Ots4gDZIAgSJ8hL0CKbIjMkm9vd0sxE0Gt+Ia/Zp3yI/yRfklNN6jKXDeIsEKxsiWSzu7rr1DlVZd98lcvMPHaClaapb9/c0IXVvF0vnc64X//WYTk33M3wU8u1dLXbyFzUS+fD7/zQoQWC57c3jTCcZSVXWpilszGFmzjDaMsbsXS2lbjvpDIOy2RrRItZ91VuymUutlUmXPswqtrKVLx2dcZrsQxgwlSmFrcfsIYbeTPuH9/caPNI17e7lXxwdfXXql2nK6lyoVyM7MmL0Urmj7uGq3XVpv5ixbO7tZKbNk8v/Ikf+fEik7VU6UURF7OCLwrs4Ra8qerH9L3CKUYfRb0Vpsr4SPNWu1qoqljIrVBFLe/dh7Ss8ly0ey8zfrhrqtYtRbUuTRr4vt6Wi7zSXc0f07Wq8gXu4GVlRKPTDO4Lteh4ntO5s5o33VWYdA+j6fZ+lPjdw/WikxpQyDZVouam2orjxsO2rzjUnyRdiUIqsRtwTh3nZIyvtKw3RiyqFoHCQS9ZFF6y5JLF/uW5RcVzisOarjBylVUqq8XoIsxnWVFMYuaPjAIoHVd4zeL48nr0+hrGDZvFl2waX44u5jzKiyJ8vjyaXl4viqoGKumq3qir0GLA26rh9tzdptaCzTQTXAPF1pUbw6q2IL6IvXeveLd7iZjlVIrAXAUBoTpCYLDRk7jQj4uoYMQIF4zYNK1Og0IxfBdr3g3hiWj9DOGBDXu2ulq3T+K596rWKMl0w+t6N3ArCebTolgY8WBc6zFC06SbrhMqgyuLWhgsdQFERlTwgrloeibe91xKfP9guAx29Cad+j4bDjUdDpXg5nrszRP2CyFBeDDWknVgfwBuMZ+FUfeAoYdebOmUUD4Y73anF3GAFwd18CnPV0l/JghNWGOLumrFke7eDNTTBuzZPcUW6AVT2iPjKj9XyDyEjf8iDlPMo0CApVjwEvN+CzrQQUxBRCtoZEgHxMaNTsnXPgy5yKTqadXKVhyzAMJ0JgBykKsTmYPQz8V6RNPwCcLDnZ9cDzulAXaGvKqcHWb1FnMlO/clu23mKnkORSM0GGIRhenC9/3ZyKdw0eOWqyvXXUP31wtLoJ7jXpjoFxnhhQJ64L8gIfj/CYK5ReBMt0cMVuejwzkt0e0dRfSPVy4QvHzqQxzr4YQlubJ7dV3SY2VjeQoVPhN+vvjg5Ks27NZgOhDYDRQnKQxktPdP2RLEz/n5Sv4+T8BDwP0f5kLS78/0dj2cIZydzkD3e8/WSw05tuujkla1zO7O5Xc2s+PtIdHMZ/OC8/N5Eyt20r9rZJdGZx5Zm3uPKyXvd6clYXyS/WqeBVmG1Fpyo3c9A9OLcJVPpjyMKGtA8MfxPIlCPqXxAjAdhyf5jNI9zDS8qo/DRZFNYx76+zfv7sRjodAgaGZT/A5l6CyEtg24CjwSmaQUaR5TLwn3+3eNQK25OqWsZEKa2vWV4Adz+tMC2VN+gtoEtT1Lsj0gcfha8kpo9HCETolCKO0qkW8ykaM7GhRIj9e7t6O3h+1O1YzSzldVQ+0Qb825JJ6+2e/f3Iz7Tudm3PdZ1NOg/QGcLdUArZcOuYRGKa+2hxECgVozLTKyehi2DmKmLVDUUuG1QFeDPezITRncfqMBV8mZZBlvee2x99SvQV8a7Z1sxOd/cjSE320qDycKbm+62983nBnkG5ZXikiJJMAZeIfyxr7bCPoq0WCRYp2qJELDc8E+/0MzYIS4C9sQornTWFVpttFIiXrENBbJlarWWCjZtgJCgATtBMwI0WalUIxIsqk/fw+7OE8HlAaX4XzLj3jY0uQwjqbOrfnKdq/wDpvlx90JL36EFBFnlvkOKxHgpVMa0+l0PL7nkN44jv3Tx2EGKqO2988rNM7YSNEOrZSdaIUiwKHTYxCwHw1t14xa4q/lw9KxyT7CX4ehTNi1rXBsIrhD65xtFOXVDyTMw2hP+6UTeNRnd9yULF8634Y+CwIv5glLiNQscPGYsNmvYN2v8caNvOB9/zbAn2H+n5zxmZE5S7xZ5sUsxJeWRyzyJiymSWMcnH7h0VO/KCGRXzZ53f6BsHvfdURfO2DnEud6KqnP33cgAoIvFSjVwD15sPqKcZuonNt//e3vx0n8RbxsRnoeLzuICtZ4YO/4JxAqBYIyGJp4scMeh+thxgzHtzmmv1eYZ1EfOukMz0GIf0E99ldFy2fPJ8zIIk2ZYkOaE3xB4H55wOtZ5H4tt1a4EOaKa1PlyGik3Z99+2PDRgXjedRobCXl3U8laEdpBLASbN2knNTQ0uRjEH1KvDDzXW/uTVw0wqQXun4Mkk8TL8lcL3I9qNCbul7ohnjZX5gPJdLsmb1GXvIp8D8m20kJ0W2TL4jYzwesXkit2bR9rhUM+tJ8jZ8fGywq44dg0b2R6ZA/36HcghKcQvZ/1ZFV0ZmGkjMNRb2GJufprYnYDPlvyhJ3+gUwf+OSv89A/o2SfxGGqlWHHl9COqSJXGYbm9H+B7jHKFu4RTHHL1V5XGzNR7ml/6D5NyNZ2zqwEQAA'
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Backup([string]$r){$p=Full $r;if(!(Test-Path -LiteralPath $p)){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};Backup $r};[IO.File]::WriteAllText($p,$c,$Utf8)}
if($env:CATALOGO_S_CONTACT_EMAIL){$e=$env:CATALOGO_S_CONTACT_EMAIL.Trim();if($e){$ConteudoModelo=[Text.RegularExpressions.Regex]::Replace($ConteudoModelo,'[A-Za-z]+@empresa\.com',[Text.RegularExpressions.MatchEvaluator]{param($m)$e})}}
if($env:CATALOGO_S_CONTACT_ENDPOINT){$e=$env:CATALOGO_S_CONTACT_ENDPOINT.Trim();if($e){$s=[System.Net.WebUtility]::HtmlEncode($e);$ConteudoModelo=$ConteudoModelo.Replace('data-contact-endpoint=""','data-contact-endpoint="'+$s+'"')}}
if($env:CATALOGO_S_WHATSAPP){$ConteudoModelo=$ConteudoModelo.Replace('https://wa.me/5500000000000',$env:CATALOGO_S_WHATSAPP.Trim())}
if($env:CATALOGO_S_INSTAGRAM){$ConteudoModelo=$ConteudoModelo.Replace('https://instagram.com/',$env:CATALOGO_S_INSTAGRAM.Trim())}
if($env:CATALOGO_S_FACEBOOK){$ConteudoModelo=$ConteudoModelo.Replace('https://facebook.com/',$env:CATALOGO_S_FACEBOOK.Trim())}
Put 'contato.html' $ConteudoModelo
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado em contato.html."
Write-Host '[Catálogo S] CTxx substitui somente contato.html e cria backup quando necessário.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
