window.CATALOGO_EFEITOS = {
  "versao": "0.2.0",
  "atualizadoEm": "2026-09-01",
  "situacao": "candidatos-curados",
  "quantidade": 75,
  "itens": [
    {
      "id": "A01",
      "nome": "Glassmorphism — Vidro Fosco",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A01-Glassmorphism-Vidro-Fosco/index.html",
      "descricao": "Demonstração contextual de Glassmorphism — Vidro Fosco. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glass",
      "bloco_pronto": "efeitos/A01-Glassmorphism-Vidro-Fosco/bloco-pronto.html"
    },
    {
      "id": "A02",
      "nome": "Vidro Escuro",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A02-Vidro-Escuro/index.html",
      "descricao": "Demonstração contextual de Vidro Escuro. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glass",
      "bloco_pronto": "efeitos/A02-Vidro-Escuro/bloco-pronto.html"
    },
    {
      "id": "A03",
      "nome": "Vidro Líquido",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A03-Vidro-Liquido/index.html",
      "descricao": "Demonstração contextual de Vidro Líquido. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glass",
      "bloco_pronto": "efeitos/A03-Vidro-Liquido/bloco-pronto.html"
    },
    {
      "id": "A06",
      "nome": "Efeito Acrílico",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A06-Efeito-Acrilico/index.html",
      "descricao": "Demonstração contextual de Efeito Acrílico. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glass",
      "bloco_pronto": "efeitos/A06-Efeito-Acrilico/bloco-pronto.html"
    },
    {
      "id": "A07",
      "nome": "Neumorfismo",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A07-Neumorfismo/index.html",
      "descricao": "Demonstração contextual de Neumorfismo. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "surface",
      "bloco_pronto": "efeitos/A07-Neumorfismo/bloco-pronto.html"
    },
    {
      "id": "A09",
      "nome": "Claymorphism",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A09-Claymorphism/index.html",
      "descricao": "Demonstração contextual de Claymorphism. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "surface",
      "bloco_pronto": "efeitos/A09-Claymorphism/bloco-pronto.html"
    },
    {
      "id": "A12",
      "nome": "Elevação Suave",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A12-Elevacao-Suave/index.html",
      "descricao": "Demonstração contextual de Elevação Suave. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "shadow",
      "bloco_pronto": "efeitos/A12-Elevacao-Suave/bloco-pronto.html"
    },
    {
      "id": "A13",
      "nome": "Sombras em Camadas",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A13-Sombras-em-Camadas/index.html",
      "descricao": "Demonstração contextual de Sombras em Camadas. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "shadow",
      "bloco_pronto": "efeitos/A13-Sombras-em-Camadas/bloco-pronto.html"
    },
    {
      "id": "A14",
      "nome": "Sombra Ambiente",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A14-Sombra-Ambiente/index.html",
      "descricao": "Demonstração contextual de Sombra Ambiente. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "shadow",
      "bloco_pronto": "efeitos/A14-Sombra-Ambiente/bloco-pronto.html"
    },
    {
      "id": "A16",
      "nome": "Sombra Colorida",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A16-Sombra-Colorida/index.html",
      "descricao": "Demonstração contextual de Sombra Colorida. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "shadow",
      "bloco_pronto": "efeitos/A16-Sombra-Colorida/bloco-pronto.html"
    },
    {
      "id": "A18",
      "nome": "Drop Shadow por Forma",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A18-Drop-Shadow-por-Forma/index.html",
      "descricao": "Demonstração contextual de Drop Shadow por Forma. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "shadow",
      "bloco_pronto": "efeitos/A18-Drop-Shadow-por-Forma/bloco-pronto.html"
    },
    {
      "id": "A20",
      "nome": "Profundidade Empilhada",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A20-Profundidade-Empilhada/index.html",
      "descricao": "Demonstração contextual de Profundidade Empilhada. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "shadow",
      "bloco_pronto": "efeitos/A20-Profundidade-Empilhada/bloco-pronto.html"
    },
    {
      "id": "A21",
      "nome": "Brilho Externo",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A21-Brilho-Externo/index.html",
      "descricao": "Demonstração contextual de Brilho Externo. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glow",
      "bloco_pronto": "efeitos/A21-Brilho-Externo/bloco-pronto.html"
    },
    {
      "id": "A24",
      "nome": "Brilho de Borda",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A24-Brilho-de-Borda/index.html",
      "descricao": "Demonstração contextual de Brilho de Borda. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glow",
      "bloco_pronto": "efeitos/A24-Brilho-de-Borda/bloco-pronto.html"
    },
    {
      "id": "A25",
      "nome": "Borda com Brilho Animado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A25-Borda-com-Brilho-Animado/index.html",
      "descricao": "Demonstração contextual de Borda com Brilho Animado. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glow",
      "bloco_pronto": "efeitos/A25-Borda-com-Brilho-Animado/bloco-pronto.html"
    },
    {
      "id": "A27",
      "nome": "Borda com Gradiente Giratório",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A27-Borda-com-Gradiente-Giratorio/index.html",
      "descricao": "Demonstração contextual de Borda com Gradiente Giratório. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glow",
      "bloco_pronto": "efeitos/A27-Borda-com-Gradiente-Giratorio/bloco-pronto.html"
    },
    {
      "id": "A28",
      "nome": "Reflexo Deslizante",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A28-Reflexo-Deslizante/index.html",
      "descricao": "Demonstração contextual de Reflexo Deslizante. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "glow",
      "bloco_pronto": "efeitos/A28-Reflexo-Deslizante/bloco-pronto.html"
    },
    {
      "id": "A30",
      "nome": "Spotlight do Cursor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A30-Spotlight-do-Cursor/index.html",
      "descricao": "Demonstração contextual de Spotlight do Cursor. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A30-Spotlight-do-Cursor/bloco-pronto.html"
    },
    {
      "id": "A35",
      "nome": "Perspectiva 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A35-Perspectiva-3D/index.html",
      "descricao": "Demonstração contextual de Perspectiva 3D. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A35-Perspectiva-3D/bloco-pronto.html"
    },
    {
      "id": "A36",
      "nome": "Card Tilt 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A36-Card-Tilt-3D/index.html",
      "descricao": "Demonstração contextual de Card Tilt 3D. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A36-Card-Tilt-3D/bloco-pronto.html"
    },
    {
      "id": "A37",
      "nome": "Parallax Tilt",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A37-Parallax-Tilt/index.html",
      "descricao": "Demonstração contextual de Parallax Tilt. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A37-Parallax-Tilt/bloco-pronto.html"
    },
    {
      "id": "A38",
      "nome": "Flip 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A38-Flip-3D/index.html",
      "descricao": "Demonstração contextual de Flip 3D. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A38-Flip-3D/bloco-pronto.html"
    },
    {
      "id": "A40",
      "nome": "Profundidade TranslateZ",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A40-Profundidade-TranslateZ/index.html",
      "descricao": "Demonstração contextual de Profundidade TranslateZ. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A40-Profundidade-TranslateZ/bloco-pronto.html"
    },
    {
      "id": "A42",
      "nome": "Carrossel Orbital",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A42-Carrossel-Orbital/index.html",
      "descricao": "Demonstração contextual de Carrossel Orbital. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A42-Carrossel-Orbital/bloco-pronto.html"
    },
    {
      "id": "A46",
      "nome": "Perspectiva pelo Mouse",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A46-Perspectiva-pelo-Mouse/index.html",
      "descricao": "Demonstração contextual de Perspectiva pelo Mouse. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "3d",
      "bloco_pronto": "efeitos/A46-Perspectiva-pelo-Mouse/bloco-pronto.html"
    },
    {
      "id": "A48",
      "nome": "Parallax Scrolling",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A48-Parallax-Scrolling/index.html",
      "descricao": "Demonstração contextual de Parallax Scrolling. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "scroll",
      "bloco_pronto": "efeitos/A48-Parallax-Scrolling/bloco-pronto.html"
    },
    {
      "id": "A49",
      "nome": "Scroll Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A49-Scroll-Reveal/index.html",
      "descricao": "Demonstração contextual de Scroll Reveal. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "scroll",
      "bloco_pronto": "efeitos/A49-Scroll-Reveal/bloco-pronto.html"
    },
    {
      "id": "A53",
      "nome": "Stagger Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A53-Stagger-Reveal/index.html",
      "descricao": "Demonstração contextual de Stagger Reveal. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "scroll",
      "bloco_pronto": "efeitos/A53-Stagger-Reveal/bloco-pronto.html"
    },
    {
      "id": "A54",
      "nome": "Scroll-Driven Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A54-Scroll-Driven-Animation/index.html",
      "descricao": "Demonstração contextual de Scroll-Driven Animation. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "scroll",
      "bloco_pronto": "efeitos/A54-Scroll-Driven-Animation/bloco-pronto.html"
    },
    {
      "id": "A56",
      "nome": "Sticky Storytelling",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A56-Sticky-Storytelling/index.html",
      "descricao": "Demonstração contextual de Sticky Storytelling. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "scroll",
      "bloco_pronto": "efeitos/A56-Sticky-Storytelling/bloco-pronto.html"
    },
    {
      "id": "A57",
      "nome": "Scroll Horizontal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A57-Scroll-Horizontal/index.html",
      "descricao": "Demonstração contextual de Scroll Horizontal. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "scroll",
      "bloco_pronto": "efeitos/A57-Scroll-Horizontal/bloco-pronto.html"
    },
    {
      "id": "A63",
      "nome": "Botão Magnético",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e interação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A63-Botao-Magnetico/index.html",
      "descricao": "Demonstração contextual de Botão Magnético. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A63-Botao-Magnetico/bloco-pronto.html"
    },
    {
      "id": "A68",
      "nome": "Preto e Branco → Cor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e interação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A68-Preto-e-Branco-Cor/index.html",
      "descricao": "Demonstração contextual de Preto e Branco → Cor. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A68-Preto-e-Branco-Cor/bloco-pronto.html"
    },
    {
      "id": "A69",
      "nome": "Zoom Interno da Imagem",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e interação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A69-Zoom-Interno-da-Imagem/index.html",
      "descricao": "Demonstração contextual de Zoom Interno da Imagem. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A69-Zoom-Interno-da-Imagem/bloco-pronto.html"
    },
    {
      "id": "A73",
      "nome": "Preview no Cursor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e interação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A73-Preview-no-Cursor/index.html",
      "descricao": "Demonstração contextual de Preview no Cursor. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A73-Preview-no-Cursor/bloco-pronto.html"
    },
    {
      "id": "A75",
      "nome": "Gradiente seguindo o Cursor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e interação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A75-Gradiente-seguindo-o-Cursor/index.html",
      "descricao": "Demonstração contextual de Gradiente seguindo o Cursor. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A75-Gradiente-seguindo-o-Cursor/bloco-pronto.html"
    },
    {
      "id": "A76",
      "nome": "Ripple",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e interação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A76-Ripple/index.html",
      "descricao": "Demonstração contextual de Ripple. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "mouse",
      "bloco_pronto": "efeitos/A76-Ripple/bloco-pronto.html"
    },
    {
      "id": "A77",
      "nome": "Crossfade",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições e revelação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A77-Crossfade/index.html",
      "descricao": "Demonstração contextual de Crossfade. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "transition",
      "bloco_pronto": "efeitos/A77-Crossfade/bloco-pronto.html"
    },
    {
      "id": "A78",
      "nome": "Slide Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições e revelação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A78-Slide-Transition/index.html",
      "descricao": "Demonstração contextual de Slide Transition. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "transition",
      "bloco_pronto": "efeitos/A78-Slide-Transition/bloco-pronto.html"
    },
    {
      "id": "A80",
      "nome": "Circular Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições e revelação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A80-Circular-Reveal/index.html",
      "descricao": "Demonstração contextual de Circular Reveal. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "transition",
      "bloco_pronto": "efeitos/A80-Circular-Reveal/bloco-pronto.html"
    },
    {
      "id": "A81",
      "nome": "Mask Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições e revelação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A81-Mask-Transition/index.html",
      "descricao": "Demonstração contextual de Mask Transition. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "transition",
      "bloco_pronto": "efeitos/A81-Mask-Transition/bloco-pronto.html"
    },
    {
      "id": "A82",
      "nome": "Shared Element Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições e revelação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A82-Shared-Element-Transition/index.html",
      "descricao": "Demonstração contextual de Shared Element Transition. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "transition",
      "bloco_pronto": "efeitos/A82-Shared-Element-Transition/bloco-pronto.html"
    },
    {
      "id": "A83",
      "nome": "View Transitions API",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições e revelação",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A83-View-Transitions-API/index.html",
      "descricao": "Demonstração contextual de View Transitions API. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "transition",
      "bloco_pronto": "efeitos/A83-View-Transitions-API/bloco-pronto.html"
    },
    {
      "id": "A91",
      "nome": "Mesh Gradient",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Fundos e gradientes",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A91-Mesh-Gradient/index.html",
      "descricao": "Demonstração contextual de Mesh Gradient. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A91-Mesh-Gradient/bloco-pronto.html"
    },
    {
      "id": "A92",
      "nome": "Gradiente Animado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Fundos e gradientes",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A92-Gradiente-Animado/index.html",
      "descricao": "Demonstração contextual de Gradiente Animado. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A92-Gradiente-Animado/bloco-pronto.html"
    },
    {
      "id": "A93",
      "nome": "Aurora Gradient",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Fundos e gradientes",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A93-Aurora-Gradient/index.html",
      "descricao": "Demonstração contextual de Aurora Gradient. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A93-Aurora-Gradient/bloco-pronto.html"
    },
    {
      "id": "A94",
      "nome": "Fundo com Glow Radial",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Fundos e gradientes",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A94-Fundo-com-Glow-Radial/index.html",
      "descricao": "Demonstração contextual de Fundo com Glow Radial. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A94-Fundo-com-Glow-Radial/bloco-pronto.html"
    },
    {
      "id": "A95",
      "nome": "Orbes de Gradiente em Movimento",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Fundos e gradientes",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A95-Orbes-de-Gradiente-em-Movimento/index.html",
      "descricao": "Demonstração contextual de Orbes de Gradiente em Movimento. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A95-Orbes-de-Gradiente-em-Movimento/bloco-pronto.html"
    },
    {
      "id": "A96",
      "nome": "Gradient Noise",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Fundos e gradientes",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A96-Gradient-Noise/index.html",
      "descricao": "Demonstração contextual de Gradient Noise. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A96-Gradient-Noise/bloco-pronto.html"
    },
    {
      "id": "A99",
      "nome": "Film Grain / Noise",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A99-Film-Grain-Noise/index.html",
      "descricao": "Demonstração contextual de Film Grain / Noise. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A99-Film-Grain-Noise/bloco-pronto.html"
    },
    {
      "id": "A104",
      "nome": "Grid Background",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A104-Grid-Background/index.html",
      "descricao": "Demonstração contextual de Grid Background. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "background",
      "bloco_pronto": "efeitos/A104-Grid-Background/bloco-pronto.html"
    },
    {
      "id": "A106",
      "nome": "Text Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A106-Text-Reveal/index.html",
      "descricao": "Demonstração contextual de Text Reveal. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "text",
      "bloco_pronto": "efeitos/A106-Text-Reveal/bloco-pronto.html"
    },
    {
      "id": "A108",
      "nome": "Character Stagger",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A108-Character-Stagger/index.html",
      "descricao": "Demonstração contextual de Character Stagger. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "text",
      "bloco_pronto": "efeitos/A108-Character-Stagger/bloco-pronto.html"
    },
    {
      "id": "A109",
      "nome": "Kinetic Typography",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A109-Kinetic-Typography/index.html",
      "descricao": "Demonstração contextual de Kinetic Typography. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "text",
      "bloco_pronto": "efeitos/A109-Kinetic-Typography/bloco-pronto.html"
    },
    {
      "id": "A110",
      "nome": "Text Scramble",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A110-Text-Scramble/index.html",
      "descricao": "Demonstração contextual de Text Scramble. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "text",
      "bloco_pronto": "efeitos/A110-Text-Scramble/bloco-pronto.html"
    },
    {
      "id": "A114",
      "nome": "Text Fill on Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A114-Text-Fill-on-Scroll/index.html",
      "descricao": "Demonstração contextual de Text Fill on Scroll. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "text",
      "bloco_pronto": "efeitos/A114-Text-Fill-on-Scroll/bloco-pronto.html"
    },
    {
      "id": "A115",
      "nome": "Marquee Text",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A115-Marquee-Text/index.html",
      "descricao": "Demonstração contextual de Marquee Text. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "text",
      "bloco_pronto": "efeitos/A115-Marquee-Text/bloco-pronto.html"
    },
    {
      "id": "A117",
      "nome": "Morphing Shapes",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A117-Morphing-Shapes/index.html",
      "descricao": "Demonstração contextual de Morphing Shapes. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "liquid",
      "bloco_pronto": "efeitos/A117-Morphing-Shapes/bloco-pronto.html"
    },
    {
      "id": "A118",
      "nome": "Blob Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A118-Blob-Animation/index.html",
      "descricao": "Demonstração contextual de Blob Animation. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "liquid",
      "bloco_pronto": "efeitos/A118-Blob-Animation/bloco-pronto.html"
    },
    {
      "id": "A119",
      "nome": "Metaballs",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A119-Metaballs/index.html",
      "descricao": "Demonstração contextual de Metaballs. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "liquid",
      "bloco_pronto": "efeitos/A119-Metaballs/bloco-pronto.html"
    },
    {
      "id": "A120",
      "nome": "Liquid Distortion",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A120-Liquid-Distortion/index.html",
      "descricao": "Demonstração contextual de Liquid Distortion. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "liquid",
      "bloco_pronto": "efeitos/A120-Liquid-Distortion/bloco-pronto.html"
    },
    {
      "id": "A122",
      "nome": "Refraction / Lens",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A122-Refraction-Lens/index.html",
      "descricao": "Demonstração contextual de Refraction / Lens. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "liquid",
      "bloco_pronto": "efeitos/A122-Refraction-Lens/bloco-pronto.html"
    },
    {
      "id": "A124",
      "nome": "Hologram",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A124-Hologram/index.html",
      "descricao": "Demonstração contextual de Hologram. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A124-Hologram/bloco-pronto.html"
    },
    {
      "id": "A126",
      "nome": "Interactive Particles",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A126-Interactive-Particles/index.html",
      "descricao": "Demonstração contextual de Interactive Particles. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A126-Interactive-Particles/bloco-pronto.html"
    },
    {
      "id": "A127",
      "nome": "Starfield 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A127-Starfield-3D/index.html",
      "descricao": "Demonstração contextual de Starfield 3D. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A127-Starfield-3D/bloco-pronto.html"
    },
    {
      "id": "A129",
      "nome": "Animated Grid Perspective",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A129-Animated-Grid-Perspective/index.html",
      "descricao": "Demonstração contextual de Animated Grid Perspective. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A129-Animated-Grid-Perspective/bloco-pronto.html"
    },
    {
      "id": "A130",
      "nome": "Chromatic Aberration",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A130-Chromatic-Aberration/index.html",
      "descricao": "Demonstração contextual de Chromatic Aberration. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A130-Chromatic-Aberration/bloco-pronto.html"
    },
    {
      "id": "A132",
      "nome": "Glitch",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A132-Glitch/index.html",
      "descricao": "Demonstração contextual de Glitch. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A132-Glitch/bloco-pronto.html"
    },
    {
      "id": "A134",
      "nome": "Scanning Beam",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A134-Scanning-Beam/index.html",
      "descricao": "Demonstração contextual de Scanning Beam. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "future",
      "bloco_pronto": "efeitos/A134-Scanning-Beam/bloco-pronto.html"
    },
    {
      "id": "A136",
      "nome": "Spring Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A136-Spring-Animation/index.html",
      "descricao": "Demonstração contextual de Spring Animation. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "micro",
      "bloco_pronto": "efeitos/A136-Spring-Animation/bloco-pronto.html"
    },
    {
      "id": "A138",
      "nome": "Smooth Press",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A138-Smooth-Press/index.html",
      "descricao": "Demonstração contextual de Smooth Press. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "micro",
      "bloco_pronto": "efeitos/A138-Smooth-Press/bloco-pronto.html"
    },
    {
      "id": "A139",
      "nome": "Icon Morph",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A139-Icon-Morph/index.html",
      "descricao": "Demonstração contextual de Icon Morph. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "micro",
      "bloco_pronto": "efeitos/A139-Icon-Morph/bloco-pronto.html"
    },
    {
      "id": "A140",
      "nome": "Animated Underline",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A140-Animated-Underline/index.html",
      "descricao": "Demonstração contextual de Animated Underline. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "micro",
      "bloco_pronto": "efeitos/A140-Animated-Underline/bloco-pronto.html"
    },
    {
      "id": "A142",
      "nome": "Button Fill",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A142-Button-Fill/index.html",
      "descricao": "Demonstração contextual de Button Fill. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "micro",
      "bloco_pronto": "efeitos/A142-Button-Fill/bloco-pronto.html"
    },
    {
      "id": "A144",
      "nome": "Shimmer",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.2",
      "caminho": "efeitos/A144-Shimmer/index.html",
      "descricao": "Demonstração contextual de Shimmer. O objeto de demonstração foi escolhido conforme a natureza do efeito, em vez de forçar uma única forma visual.",
      "codigo_copiavel": true,
      "demonstracao": "contextual",
      "tipo_demonstracao": "micro",
      "bloco_pronto": "efeitos/A144-Shimmer/bloco-pronto.html"
    }
  ]
};
