window.CATALOGO_EFEITOS = {
  "versao": "0.1.0",
  "atualizadoEm": "2026-09-01",
  "situacao": "candidatos",
  "itens": [
    {
      "id": "A01",
      "nome": "Glassmorphism — Vidro Fosco",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A01-Glassmorphism-Vidro-Fosco/index.html",
      "descricao": "Demonstração isolada do efeito Glassmorphism — Vidro Fosco usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A02",
      "nome": "Vidro Escuro",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A02-Vidro-Escuro/index.html",
      "descricao": "Demonstração isolada do efeito Vidro Escuro usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A03",
      "nome": "Vidro Líquido",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A03-Vidro-Liquido/index.html",
      "descricao": "Demonstração isolada do efeito Vidro Líquido usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A04",
      "nome": "Vidro Brilhante",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A04-Vidro-Brilhante/index.html",
      "descricao": "Demonstração isolada do efeito Vidro Brilhante usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A05",
      "nome": "Vidro Fosco Intenso",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A05-Vidro-Fosco-Intenso/index.html",
      "descricao": "Demonstração isolada do efeito Vidro Fosco Intenso usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A06",
      "nome": "Efeito Acrílico",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A06-Efeito-Acrilico/index.html",
      "descricao": "Demonstração isolada do efeito Efeito Acrílico usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A07",
      "nome": "Neumorfismo",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A07-Neumorfismo/index.html",
      "descricao": "Demonstração isolada do efeito Neumorfismo usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A08",
      "nome": "Relevo Interno / Pressionado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A08-Relevo-Interno-Pressionado/index.html",
      "descricao": "Demonstração isolada do efeito Relevo Interno / Pressionado usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A09",
      "nome": "Claymorphism",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A09-Claymorphism/index.html",
      "descricao": "Demonstração isolada do efeito Claymorphism usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A10",
      "nome": "Skeuomorfismo Moderno",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Vidro e materiais",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A10-Skeuomorfismo-Moderno/index.html",
      "descricao": "Demonstração isolada do efeito Skeuomorfismo Moderno usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A11",
      "nome": "Elevação no Hover",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A11-Elevacao-no-Hover/index.html",
      "descricao": "Demonstração isolada do efeito Elevação no Hover usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A12",
      "nome": "Elevação Suave",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A12-Elevacao-Suave/index.html",
      "descricao": "Demonstração isolada do efeito Elevação Suave usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A13",
      "nome": "Sombras em Camadas",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A13-Sombras-em-Camadas/index.html",
      "descricao": "Demonstração isolada do efeito Sombras em Camadas usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A14",
      "nome": "Sombra Ambiente",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A14-Sombra-Ambiente/index.html",
      "descricao": "Demonstração isolada do efeito Sombra Ambiente usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A15",
      "nome": "Sombra Direcional",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A15-Sombra-Direcional/index.html",
      "descricao": "Demonstração isolada do efeito Sombra Direcional usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A16",
      "nome": "Sombra Colorida",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A16-Sombra-Colorida/index.html",
      "descricao": "Demonstração isolada do efeito Sombra Colorida usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A17",
      "nome": "Sombra com Brilho",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A17-Sombra-com-Brilho/index.html",
      "descricao": "Demonstração isolada do efeito Sombra com Brilho usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A18",
      "nome": "Drop Shadow por Forma",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A18-Drop-Shadow-por-Forma/index.html",
      "descricao": "Demonstração isolada do efeito Drop Shadow por Forma usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A19",
      "nome": "Cards Flutuantes",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A19-Cards-Flutuantes/index.html",
      "descricao": "Demonstração isolada do efeito Cards Flutuantes usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A20",
      "nome": "Profundidade Empilhada",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Profundidade e sombras",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A20-Profundidade-Empilhada/index.html",
      "descricao": "Demonstração isolada do efeito Profundidade Empilhada usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A21",
      "nome": "Brilho Externo",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A21-Brilho-Externo/index.html",
      "descricao": "Demonstração isolada do efeito Brilho Externo usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A22",
      "nome": "Brilho Interno",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A22-Brilho-Interno/index.html",
      "descricao": "Demonstração isolada do efeito Brilho Interno usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A23",
      "nome": "Neon Glow",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A23-Neon-Glow/index.html",
      "descricao": "Demonstração isolada do efeito Neon Glow usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A24",
      "nome": "Brilho de Borda",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A24-Brilho-de-Borda/index.html",
      "descricao": "Demonstração isolada do efeito Brilho de Borda usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A25",
      "nome": "Borda com Brilho Animado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A25-Borda-com-Brilho-Animado/index.html",
      "descricao": "Demonstração isolada do efeito Borda com Brilho Animado usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A26",
      "nome": "Borda em Gradiente",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A26-Borda-em-Gradiente/index.html",
      "descricao": "Demonstração isolada do efeito Borda em Gradiente usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A27",
      "nome": "Borda com Gradiente Giratório",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A27-Borda-com-Gradiente-Giratorio/index.html",
      "descricao": "Demonstração isolada do efeito Borda com Gradiente Giratório usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A28",
      "nome": "Reflexo Deslizante",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A28-Reflexo-Deslizante/index.html",
      "descricao": "Demonstração isolada do efeito Reflexo Deslizante usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A29",
      "nome": "Reflexo Especular",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A29-Reflexo-Especular/index.html",
      "descricao": "Demonstração isolada do efeito Reflexo Especular usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A30",
      "nome": "Spotlight do Cursor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A30-Spotlight-do-Cursor/index.html",
      "descricao": "Demonstração isolada do efeito Spotlight do Cursor usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A31",
      "nome": "Efeito Lanterna",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A31-Efeito-Lanterna/index.html",
      "descricao": "Demonstração isolada do efeito Efeito Lanterna usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A32",
      "nome": "Bloom",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A32-Bloom/index.html",
      "descricao": "Demonstração isolada do efeito Bloom usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A33",
      "nome": "Brilho Holográfico",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A33-Brilho-Holografico/index.html",
      "descricao": "Demonstração isolada do efeito Brilho Holográfico usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A34",
      "nome": "Iridescência",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Luz e brilho",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A34-Iridescencia/index.html",
      "descricao": "Demonstração isolada do efeito Iridescência usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A35",
      "nome": "Perspectiva 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A35-Perspectiva-3D/index.html",
      "descricao": "Demonstração isolada do efeito Perspectiva 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A36",
      "nome": "Card Tilt 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A36-Card-Tilt-3D/index.html",
      "descricao": "Demonstração isolada do efeito Card Tilt 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A37",
      "nome": "Parallax Tilt",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A37-Parallax-Tilt/index.html",
      "descricao": "Demonstração isolada do efeito Parallax Tilt usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A38",
      "nome": "Flip 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A38-Flip-3D/index.html",
      "descricao": "Demonstração isolada do efeito Flip 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A39",
      "nome": "Rotação X/Y",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A39-Rotacao-X-Y/index.html",
      "descricao": "Demonstração isolada do efeito Rotação X/Y usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A40",
      "nome": "Profundidade TranslateZ",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A40-Profundidade-TranslateZ/index.html",
      "descricao": "Demonstração isolada do efeito Profundidade TranslateZ usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A41",
      "nome": "Carrossel 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A41-Carrossel-3D/index.html",
      "descricao": "Demonstração isolada do efeito Carrossel 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A42",
      "nome": "Carrossel Orbital",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A42-Carrossel-Orbital/index.html",
      "descricao": "Demonstração isolada do efeito Carrossel Orbital usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A43",
      "nome": "Anel 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A43-Anel-3D/index.html",
      "descricao": "Demonstração isolada do efeito Anel 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A44",
      "nome": "Cubo 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A44-Cubo-3D/index.html",
      "descricao": "Demonstração isolada do efeito Cubo 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A45",
      "nome": "Pilha 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A45-Pilha-3D/index.html",
      "descricao": "Demonstração isolada do efeito Pilha 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A46",
      "nome": "Perspectiva pelo Mouse",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A46-Perspectiva-pelo-Mouse/index.html",
      "descricao": "Demonstração isolada do efeito Perspectiva pelo Mouse usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A47",
      "nome": "Objeto 3D no Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "3D e perspectiva",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A47-Objeto-3D-no-Scroll/index.html",
      "descricao": "Demonstração isolada do efeito Objeto 3D no Scroll usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A48",
      "nome": "Parallax Scrolling",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A48-Parallax-Scrolling/index.html",
      "descricao": "Demonstração isolada do efeito Parallax Scrolling usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A49",
      "nome": "Scroll Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A49-Scroll-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Scroll Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A50",
      "nome": "Fade + Translate Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A50-Fade-Translate-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Fade + Translate Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A51",
      "nome": "Scale Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A51-Scale-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Scale Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A52",
      "nome": "Blur Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A52-Blur-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Blur Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A53",
      "nome": "Stagger Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A53-Stagger-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Stagger Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A54",
      "nome": "Scroll-Driven Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A54-Scroll-Driven-Animation/index.html",
      "descricao": "Demonstração isolada do efeito Scroll-Driven Animation usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A55",
      "nome": "Scrollytelling",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A55-Scrollytelling/index.html",
      "descricao": "Demonstração isolada do efeito Scrollytelling usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A56",
      "nome": "Sticky Storytelling",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A56-Sticky-Storytelling/index.html",
      "descricao": "Demonstração isolada do efeito Sticky Storytelling usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A57",
      "nome": "Scroll Horizontal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A57-Scroll-Horizontal/index.html",
      "descricao": "Demonstração isolada do efeito Scroll Horizontal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A58",
      "nome": "Scroll Snap",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A58-Scroll-Snap/index.html",
      "descricao": "Demonstração isolada do efeito Scroll Snap usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A59",
      "nome": "Progresso de Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A59-Progresso-de-Scroll/index.html",
      "descricao": "Demonstração isolada do efeito Progresso de Scroll usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A60",
      "nome": "Zoom no Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A60-Zoom-no-Scroll/index.html",
      "descricao": "Demonstração isolada do efeito Zoom no Scroll usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A61",
      "nome": "Rotação no Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A61-Rotacao-no-Scroll/index.html",
      "descricao": "Demonstração isolada do efeito Rotação no Scroll usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A62",
      "nome": "Profundidade no Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Scroll e movimento",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A62-Profundidade-no-Scroll/index.html",
      "descricao": "Demonstração isolada do efeito Profundidade no Scroll usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A63",
      "nome": "Botão Magnético",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A63-Botao-Magnetico/index.html",
      "descricao": "Demonstração isolada do efeito Botão Magnético usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A64",
      "nome": "Card Magnético",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A64-Card-Magnetico/index.html",
      "descricao": "Demonstração isolada do efeito Card Magnético usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A65",
      "nome": "Hover Lift",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A65-Hover-Lift/index.html",
      "descricao": "Demonstração isolada do efeito Hover Lift usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A66",
      "nome": "Hover Scale",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A66-Hover-Scale/index.html",
      "descricao": "Demonstração isolada do efeito Hover Scale usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A67",
      "nome": "Hover Rotate",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A67-Hover-Rotate/index.html",
      "descricao": "Demonstração isolada do efeito Hover Rotate usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A68",
      "nome": "Preto e Branco → Cor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A68-Preto-e-Branco-Cor/index.html",
      "descricao": "Demonstração isolada do efeito Preto e Branco → Cor usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A69",
      "nome": "Zoom Interno da Imagem",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A69-Zoom-Interno-da-Imagem/index.html",
      "descricao": "Demonstração isolada do efeito Zoom Interno da Imagem usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A70",
      "nome": "Pan de Imagem",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A70-Pan-de-Imagem/index.html",
      "descricao": "Demonstração isolada do efeito Pan de Imagem usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A71",
      "nome": "Cursor Follower",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A71-Cursor-Follower/index.html",
      "descricao": "Demonstração isolada do efeito Cursor Follower usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A72",
      "nome": "Cursor Personalizado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A72-Cursor-Personalizado/index.html",
      "descricao": "Demonstração isolada do efeito Cursor Personalizado usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A73",
      "nome": "Preview no Cursor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A73-Preview-no-Cursor/index.html",
      "descricao": "Demonstração isolada do efeito Preview no Cursor usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A74",
      "nome": "Revelação no Hover",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A74-Revelacao-no-Hover/index.html",
      "descricao": "Demonstração isolada do efeito Revelação no Hover usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A75",
      "nome": "Gradiente seguindo o Cursor",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A75-Gradiente-seguindo-o-Cursor/index.html",
      "descricao": "Demonstração isolada do efeito Gradiente seguindo o Cursor usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A76",
      "nome": "Ripple",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Mouse e hover",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A76-Ripple/index.html",
      "descricao": "Demonstração isolada do efeito Ripple usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A77",
      "nome": "Crossfade",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A77-Crossfade/index.html",
      "descricao": "Demonstração isolada do efeito Crossfade usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A78",
      "nome": "Slide Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A78-Slide-Transition/index.html",
      "descricao": "Demonstração isolada do efeito Slide Transition usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A79",
      "nome": "Scale Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A79-Scale-Transition/index.html",
      "descricao": "Demonstração isolada do efeito Scale Transition usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A80",
      "nome": "Circular Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A80-Circular-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Circular Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A81",
      "nome": "Mask Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A81-Mask-Transition/index.html",
      "descricao": "Demonstração isolada do efeito Mask Transition usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A82",
      "nome": "Shared Element Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A82-Shared-Element-Transition/index.html",
      "descricao": "Demonstração isolada do efeito Shared Element Transition usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A83",
      "nome": "View Transitions API",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Transições",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A83-View-Transitions-API/index.html",
      "descricao": "Demonstração isolada do efeito View Transitions API usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A84",
      "nome": "Clip-Path Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A84-Clip-Path-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Clip-Path Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A85",
      "nome": "Mask Image Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A85-Mask-Image-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Mask Image Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A86",
      "nome": "Curtain Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A86-Curtain-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Curtain Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A87",
      "nome": "Diagonal Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A87-Diagonal-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Diagonal Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A88",
      "nome": "Image Slice Transition",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A88-Image-Slice-Transition/index.html",
      "descricao": "Demonstração isolada do efeito Image Slice Transition usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A89",
      "nome": "Spot Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A89-Spot-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Spot Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A90",
      "nome": "Before/After Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Máscaras e revelação",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A90-Before-After-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Before/After Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A91",
      "nome": "Mesh Gradient",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A91-Mesh-Gradient/index.html",
      "descricao": "Demonstração isolada do efeito Mesh Gradient usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A92",
      "nome": "Gradiente Animado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A92-Gradiente-Animado/index.html",
      "descricao": "Demonstração isolada do efeito Gradiente Animado usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A93",
      "nome": "Aurora Gradient",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A93-Aurora-Gradient/index.html",
      "descricao": "Demonstração isolada do efeito Aurora Gradient usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A94",
      "nome": "Fundo com Glow Radial",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A94-Fundo-com-Glow-Radial/index.html",
      "descricao": "Demonstração isolada do efeito Fundo com Glow Radial usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A95",
      "nome": "Orbes de Gradiente em Movimento",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A95-Orbes-de-Gradiente-em-Movimento/index.html",
      "descricao": "Demonstração isolada do efeito Orbes de Gradiente em Movimento usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A96",
      "nome": "Gradient Noise",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A96-Gradient-Noise/index.html",
      "descricao": "Demonstração isolada do efeito Gradient Noise usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A97",
      "nome": "Texto com Gradiente",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A97-Texto-com-Gradiente/index.html",
      "descricao": "Demonstração isolada do efeito Texto com Gradiente usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A98",
      "nome": "Texto com Gradiente Animado",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Gradientes e fundos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A98-Texto-com-Gradiente-Animado/index.html",
      "descricao": "Demonstração isolada do efeito Texto com Gradiente Animado usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A99",
      "nome": "Film Grain / Noise",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A99-Film-Grain-Noise/index.html",
      "descricao": "Demonstração isolada do efeito Film Grain / Noise usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A100",
      "nome": "Paper Grain",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A100-Paper-Grain/index.html",
      "descricao": "Demonstração isolada do efeito Paper Grain usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A101",
      "nome": "Dither",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A101-Dither/index.html",
      "descricao": "Demonstração isolada do efeito Dither usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A102",
      "nome": "Halftone",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A102-Halftone/index.html",
      "descricao": "Demonstração isolada do efeito Halftone usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A103",
      "nome": "Scanlines",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A103-Scanlines/index.html",
      "descricao": "Demonstração isolada do efeito Scanlines usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A104",
      "nome": "Grid Background",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A104-Grid-Background/index.html",
      "descricao": "Demonstração isolada do efeito Grid Background usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A105",
      "nome": "Dot Grid",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texturas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A105-Dot-Grid/index.html",
      "descricao": "Demonstração isolada do efeito Dot Grid usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A106",
      "nome": "Text Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A106-Text-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Text Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A107",
      "nome": "Line-by-Line Reveal",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A107-Line-by-Line-Reveal/index.html",
      "descricao": "Demonstração isolada do efeito Line-by-Line Reveal usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A108",
      "nome": "Character Stagger",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A108-Character-Stagger/index.html",
      "descricao": "Demonstração isolada do efeito Character Stagger usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A109",
      "nome": "Kinetic Typography",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A109-Kinetic-Typography/index.html",
      "descricao": "Demonstração isolada do efeito Kinetic Typography usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A110",
      "nome": "Text Scramble",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A110-Text-Scramble/index.html",
      "descricao": "Demonstração isolada do efeito Text Scramble usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A111",
      "nome": "Typewriter",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A111-Typewriter/index.html",
      "descricao": "Demonstração isolada do efeito Typewriter usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A112",
      "nome": "Text Glow",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A112-Text-Glow/index.html",
      "descricao": "Demonstração isolada do efeito Text Glow usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A113",
      "nome": "Outlined Text",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A113-Outlined-Text/index.html",
      "descricao": "Demonstração isolada do efeito Outlined Text usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A114",
      "nome": "Text Fill on Scroll",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A114-Text-Fill-on-Scroll/index.html",
      "descricao": "Demonstração isolada do efeito Text Fill on Scroll usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A115",
      "nome": "Marquee Text",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A115-Marquee-Text/index.html",
      "descricao": "Demonstração isolada do efeito Marquee Text usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A116",
      "nome": "Variable Font Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Texto e tipografia",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A116-Variable-Font-Animation/index.html",
      "descricao": "Demonstração isolada do efeito Variable Font Animation usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A117",
      "nome": "Morphing Shapes",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A117-Morphing-Shapes/index.html",
      "descricao": "Demonstração isolada do efeito Morphing Shapes usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A118",
      "nome": "Blob Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A118-Blob-Animation/index.html",
      "descricao": "Demonstração isolada do efeito Blob Animation usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A119",
      "nome": "Metaballs",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A119-Metaballs/index.html",
      "descricao": "Demonstração isolada do efeito Metaballs usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A120",
      "nome": "Liquid Distortion",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A120-Liquid-Distortion/index.html",
      "descricao": "Demonstração isolada do efeito Liquid Distortion usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A121",
      "nome": "Ripple Distortion",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A121-Ripple-Distortion/index.html",
      "descricao": "Demonstração isolada do efeito Ripple Distortion usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A122",
      "nome": "Refraction / Lens",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A122-Refraction-Lens/index.html",
      "descricao": "Demonstração isolada do efeito Refraction / Lens usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A123",
      "nome": "Magnifying Glass",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Formas e líquidos",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A123-Magnifying-Glass/index.html",
      "descricao": "Demonstração isolada do efeito Magnifying Glass usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A124",
      "nome": "Hologram",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A124-Hologram/index.html",
      "descricao": "Demonstração isolada do efeito Hologram usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A125",
      "nome": "Particle Field",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A125-Particle-Field/index.html",
      "descricao": "Demonstração isolada do efeito Particle Field usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A126",
      "nome": "Interactive Particles",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A126-Interactive-Particles/index.html",
      "descricao": "Demonstração isolada do efeito Interactive Particles usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A127",
      "nome": "Starfield 3D",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A127-Starfield-3D/index.html",
      "descricao": "Demonstração isolada do efeito Starfield 3D usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A128",
      "nome": "Energy Lines",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A128-Energy-Lines/index.html",
      "descricao": "Demonstração isolada do efeito Energy Lines usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A129",
      "nome": "Animated Grid Perspective",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A129-Animated-Grid-Perspective/index.html",
      "descricao": "Demonstração isolada do efeito Animated Grid Perspective usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A130",
      "nome": "Chromatic Aberration",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A130-Chromatic-Aberration/index.html",
      "descricao": "Demonstração isolada do efeito Chromatic Aberration usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A131",
      "nome": "RGB Split Hover",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A131-RGB-Split-Hover/index.html",
      "descricao": "Demonstração isolada do efeito RGB Split Hover usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A132",
      "nome": "Glitch",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A132-Glitch/index.html",
      "descricao": "Demonstração isolada do efeito Glitch usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A133",
      "nome": "Data Stream / Matrix",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A133-Data-Stream-Matrix/index.html",
      "descricao": "Demonstração isolada do efeito Data Stream / Matrix usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A134",
      "nome": "Scanning Beam",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Futuristas",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A134-Scanning-Beam/index.html",
      "descricao": "Demonstração isolada do efeito Scanning Beam usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A135",
      "nome": "Microinteractions",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A135-Microinteractions/index.html",
      "descricao": "Demonstração isolada do efeito Microinteractions usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A136",
      "nome": "Spring Animation",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A136-Spring-Animation/index.html",
      "descricao": "Demonstração isolada do efeito Spring Animation usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A137",
      "nome": "Elastic Hover",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A137-Elastic-Hover/index.html",
      "descricao": "Demonstração isolada do efeito Elastic Hover usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A138",
      "nome": "Smooth Press",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A138-Smooth-Press/index.html",
      "descricao": "Demonstração isolada do efeito Smooth Press usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A139",
      "nome": "Icon Morph",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A139-Icon-Morph/index.html",
      "descricao": "Demonstração isolada do efeito Icon Morph usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A140",
      "nome": "Animated Underline",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A140-Animated-Underline/index.html",
      "descricao": "Demonstração isolada do efeito Animated Underline usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A141",
      "nome": "Underline Follow",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A141-Underline-Follow/index.html",
      "descricao": "Demonstração isolada do efeito Underline Follow usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A142",
      "nome": "Button Fill",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A142-Button-Fill/index.html",
      "descricao": "Demonstração isolada do efeito Button Fill usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A143",
      "nome": "Arrow Motion",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A143-Arrow-Motion/index.html",
      "descricao": "Demonstração isolada do efeito Arrow Motion usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    },
    {
      "id": "A144",
      "nome": "Shimmer",
      "tipo": "Frontend",
      "categoria": "Efeito",
      "familia": "Microinterações",
      "situacao": "Candidato",
      "versao": "0.1",
      "caminho": "efeitos/A144-Shimmer/index.html",
      "descricao": "Demonstração isolada do efeito Shimmer usando a composição padrão de três círculos.",
      "codigo_copiavel": true
    }
  ]
};
