# Normaliza páginas que no catálogo são armazenadas como fragmentos visuais.
# CTxx já fornece um documento HTML completo para a página canônica contato.html.
$ModeloId='CT04'
$ModeloNome='Contato Bento com Disponibilidade'
$Payload='H4sIAJ2dmWoC/5VYXZLjthF+31MgnNoaKRElkhJnJFJSbK/Xcary5HWq8goRoASbJGgA1MxYpVQO4Qts5SEVV+UxJ9BNcpJ0A6T+ZnY22a0SSRDo/rr76x/O/DdMZuap5mRjymL5Zo4XUtBqvfBq43/1nUcYNdTP4KeQa+lrv5SMFwvv3ffBxFvON5yy5bzkhpJsQ5XmZuE1JvenXrta0ZIvvK3gD7VUxiOZrAyvYNeDYGazYHwrMu7bh4GohBG08HVGC74IQYQRpuDLd3CGGjkfucc3c22e8Prb3Uo++lr8LKp1spKKceXDyh6NGKwke9qVVK1FlQTpimY/rpVsKpbcBDwMwnGayUKq5CaP4f84zUGHn9NSFE/JlwpQDL7lxZYbkdGBppX2NVciT+WWq7yQD/5jshGM8Wo/zEww2ZWi8jdcrDcmCYNAbzdpTRlDXFlBy7oX3dWPg3j7MLiP6sd+yoSuC/qUrJVgKdyBC4ThpU4y8A1X53ALUXGq/LWiTMDLXjiJGV8PbgIW5GE0uAnjcBqy/n74oGi9s45MAE0vDKcB6AQ0b+ElxmnXac0L/pj+0Ggj8ie/DUiia0Sx4uaB8ypd0zoZw/mUFmJdteB4xVLnUXCzMbK0W5xwsgl36MPkLgiIs3kyAf13aDMY3x8NZzH5A5dwHDxqndlFp5VQQ7geHRWSSYTK2xDNGB1TlqInjk4e3sX74QqAy92FM/HHB7SwYjgYVzRlpWF7FOeKDO/t7zRXV/uUfNBJFINOElnNaH94h8YZUfCdI1cSwnstC8HITW7/hZMLZrnFYJq2ZMSYNSAYHHHkg3uQGqguq0Rx0C+2/EisI61yqcqdRQngknA0Ti/Chz8+E4pnVo4z1J0im2hgYcPNMQNIQGZojt1Qt+/rXefhjE4ov/JwHLfbLZRLL6N7gMkdHYysE9oY2R4QVd2Ygbs3/NFQxWlLTeRj+kl33l0magapGh0TNc+v/GoRdH4Nx/AgG4M2JJWs+P5K/2WKwmbFoXRc7F01wOqqi3bwkrqLcEd5wKcdvjAMT2AwyLakPDiN0yBIs0Zp2FhLgTm+H2ooaiB2xUE333V56HkndtAVuKcxPG19hxmddjbYh0uEMfr2DGAcsmiajeM0FwWoTFZFo2wp6qfKCvHvUQhGz97th0yaY6RFZfmwKmT2Y4tgdtI/u3JGPGFsFr4ECGv0hjJgMbIQs4p0u1v6ODBTBLAS61MdmYDHR+HLVSOCdyDO5mgJle+1kjl2JTO8D1dRANcgjMK4b8/9T+4XFTS2yy5yraPL/RkBVg+MgpZRA+0qg8/9wfX2WWARvXroTJ1vmTpGk/EntVuRsknNla6xCGx5L0Za94mSQCz+l14YgY4+sd20Fw7B4lRCkRfmKRlO98NaVLvnphY8N0kcv7WkmEzfHql3zrwj8ZL4PIWz7H78eQIABbDOtvtDQLKRkBmkKXaF0Ma3zd1m5TGdgmPQAxv0oDtTiP+nqXXiZigkPQ4MtpM9r0VBl9irMQQiculs44Cl5oQgKSigzjaiYLtLmQATgdDMEG2UrByznYwIy1WH3aXYWS0dT1BDd5i+nJJn+8OzbpnfsXi6SrHu+YxnUlEbYVvm3nxRciZo79RoZ5Yzu7aVfqJ7QtMMX+6Zp6J/6lW45vY6AdC8fEj1U/mduLHBdtazZdt59/tnEOM7B9HOMOfzCBRQZT7VCT9j0DnoFqaz5Rmq0KJ6Mx+5qXM+cjMvzpcw41JR4bij9cLDQRBmVia23QqOZB5O1XCCq24Vn3B0DrvBdkA0L4lqDv9icgjyw+W8Xv4Z2jQI5wVh3E7NsBGuYAmHGygTlIBZ0MOoJj810MvBAULTkpQSyEaV7dpNcfioBChAAslKrAQwHLAMCDAIXPkzPfzj8HdJOLRs3I+P/+YahB0+4uirYX4nJdclhT5aUABXtw7gCudw5/POMOtytBfCIjKYL9p1O2ugeLQ6slZzIi3qrcwOv3bYQXKEpn+vDr9qksEMKfWQfADfZJRRTCH3BDVv3YBDNLhGVzzjWqOZVDt8bgRhLiB+q9eOJKdV/CzxiJ28N7IAaxbeB96QSuKy4j81wCf27BSHcBcewQ+mhdc+PJPBfffiJKUbQU6CwKWarq8RvJMlRBa+ryCEhP7QMKp+fy5n1AkC9tlJpUWim1UpjLd8X20FBB7LGFR5F9r5yG1dzqEWVicEOHyAfgpu8wtoHvC9B8dgCdTgTrig5+DSBvMTYXVDjAusU9G+hUniKOtLKMZMlEgPIm0Jc6E+SxXo+97yryTazEewalkA9JakPPyTCYk5UCuQIID2wHkgBnxbsgbaoKXSRipLdEwQrjL4fGup+jp46P+dC+gKv2q/45hRgLPNi63QDbUZeJEv3qWp0EnP3Pa6Sts1nLu+bUFr54ymWM4L4SQvP/A1+c/ffgG6P3aCXQtZBtMEJiN8F+IdliW7Ph/h4ZOAw8cVtNzrw7Pj4fErh7+WUADX14e/4dnGiTw/NELcnzG6bWSn9MdahiUbP+otcZzEtsx90RY2aIDlSRslG8VzkMiL5HcxzDrHf94SnkkvCPrEPvv4A5gucI3aYrVsCTbC0g2aMyVqs2Qya5CfwzU37wuOt189/ZH1bo815LY/hPHh/Rbe/AnGFF5x1bt1mXc74Ivljg8BNL7+mue0KUwPPvNflWpTEMRiVr9r/yxy++E8ebEwYqVn1MYMC0OFxd2+HN7u+2CVww9pbvvRyP4d578CQRlK1xEAAA=='
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Backup([string]$r){$p=Full $r;if(!(Test-Path -LiteralPath $p)){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};Backup $r};[IO.File]::WriteAllText($p,$c,$Utf8)}
if($env:CATALOGO_S_CONTACT_EMAIL){$e=$env:CATALOGO_S_CONTACT_EMAIL.Trim();if($e){$ConteudoModelo=[Text.RegularExpressions.Regex]::Replace($ConteudoModelo,'[A-Za-z]+@empresa\.com',[Text.RegularExpressions.MatchEvaluator]{param($m)$e})}}
if($env:CATALOGO_S_CONTACT_ENDPOINT){$e=$env:CATALOGO_S_CONTACT_ENDPOINT.Trim();if($e){$s=[System.Net.WebUtility]::HtmlEncode($e);$ConteudoModelo=$ConteudoModelo.Replace('data-contact-endpoint=""','data-contact-endpoint="'+$s+'"')}}
if($env:CATALOGO_S_WHATSAPP){$ConteudoModelo=$ConteudoModelo.Replace('https://wa.me/5500000000000',$env:CATALOGO_S_WHATSAPP.Trim())}
if($env:CATALOGO_S_INSTAGRAM){$ConteudoModelo=$ConteudoModelo.Replace('https://instagram.com/',$env:CATALOGO_S_INSTAGRAM.Trim())}
if($env:CATALOGO_S_FACEBOOK){$ConteudoModelo=$ConteudoModelo.Replace('https://facebook.com/',$env:CATALOGO_S_FACEBOOK.Trim())}
Put 'contato.html' $ConteudoModelo
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado em contato.html."
Write-Host '[Catálogo S] CTxx substitui somente contato.html e cria backup quando necessário.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
