$ModeloId='F03'
$ModeloNome='Mega Rodapé de E-commerce'
$Payload='H4sIAAKKmWoC/6VY3W7juBW+n6cgnJuksGLJf3Fkx2gwzXT3Ynam9bRoLynxyOaMJGpJynFqBNh32Bfo3WIL9KpYLLCXmzfZJ+kh5R/ZkjyeNkAcixTPz3e+85HMJBJCgySc3bVCqmks5sKJ3F6LMHxydkPKSQSD+K71BuemryZKP8UwfXVRXrN2nGDuX7jM87ybseNkNIXYv/AGXtDt4bOGlfYvgEVeNMDHJNfA/ItRdHtLR/gc8xT8i8j+eH07kOBAOIq6w9txQMNPcynylPlLKi+Nq6txKGIhN8/G+tU4Eql2Iprw+Mm/l5zG7a8gXoLmIW0rmipHgeTR82Hg5HfrQKwcxf/B07kfCMlAOjjyfPgWXRf+eLpAI3psPDoMQiGp5iL1U5HCseVr/HACSCHiWq0ZV1lMn/y55GxsPjDqBEc0OGg6T1LlS8iA6st+24vk1XgTixaZ72UrokTMGSnyNXDtXgiE1iKpf+dUSOuMMmaS7vZxaRjTJLv0Rtmq3Vs+tvvdbLXzIPl8oRscNNv3Y6q0Ey54zNYHhtxTUZFgh1QQi/DTOKFyztNtloNsVdQZCwa+h1GeiIAopOG6TBTLu6uyBcyqNhyE/ZySYaUI/o7nNPMHLga3BbU/2oFq8G0PENSRa0Hds9lASKUzl5RxSDXC7zKYty88FxsnbG/aqb6KKTwqsuiuC3x8l7jkdgMORuJufPfQZbtvCorxXHU88kcQ+D42hO2FJrtZ2WzX5HUaxV4DipGQyQ7GKIYVlnPlPHKmF/7AwLGhWIlcGxXoujv2ITi5srXeoTs0K/c4bta4o8YgCE+zXK8TZFLh3R2bcHxvG4BbtqclykVGJdZkk7jxMBa5tkJlmn0XiodZkCYiWtdBjtRN13tHB3mNDlPZ9lYCW4m7QA4MXXrkcLRthEewTXXruuMwlwoXZIKnqOu1WNAsU4cFoTGfpw5HZis74EDKxh9zpXn0hDRHS0io3YThuQnAouc8Snw0H02+SoB7/UFduWsEbVtwr1RwAzDx+vVlHz7XeycqoXF8pCcniWxQtdJuGWCq5+dZBjKkCpqcBOtSI/QbGiGBOT1LT667A5SUzU4wKHYCA3qvXxaXYaO4fGbTqJdeTJYRpaVI5+udgHSNgn1WLoq1Ri+2fd1zw8Vn5MK0sgnHWRTk9a6Hg9rI0AxZ9MpiZDlQMmW4GINGvjvYsaFB59rrQdJYxm1XsREDGD03OKVHrNkijxwm7tbELaM3weCM/cha9BdiCfJgO7JtXr/9SOzAw0Y97kmTLuBWpx8B0oM2DsH0f9GroxJtjJD/b7Q556zxmZq7DZ2R0afDPE3YN1WF2b5cbOpfoCPDEgI3RkXcqorspHbUdbu0Iqz7NG4bsiiA+ZKCmTS77lnV2QQ3HN30Rv1jTBuDISldVpH1hjXi/fsEGKeX+x6+tY7Xp86zJ89Dp46FqV4Up8LL7tXxwbBJOZvEsr/Xyp7VyueaZG7cpmTMIa8xj+em7bN2c1SaSv2l8Z8Ay8hqsax42/c6jvfcpBTtZkpW9ncbaUEBxiWE9v5SOKlDr/9/UOEEDY4qf9Zl5ovRPQ9ZmmuBmU86m4vthPGlaUSl7lrlPFvThhmcCKZvJGgg5uSFgBsBnnSC6cSI1fS1SBl/+eHlJ1AEVjzgjCqSChIuIPyEh0r0bF6bdND8SR8fpAgpURwz5RFeaxndO3kT5ythFkpBgJROsHC2+dciySQlmRQa5rxs/D4JzAUF0HJG5zTB70IRBfNcCnW2/VmeCYlGFnlCU1Gy/jFnlHybY2EEWYrw5V8YA4RcUXlo235W6oNdjOZVweTyhLnK4MyiO31ItTShY3aUxBxb4HrSwfFJNv1GLDFVBqpNYpq+/LBNDojt75dfmM00xnhESvEBV2bTiT3Zl3yZZ/RlrxlEP2Vw14KE8rhFqOTUiWlg/oPy4BRjyNQQFiJGyt+1ZpCTBOKFkASKeQTL3hk2hoqH1vRPOWBxERkIAJEphhEV4xv/bBColMCIVqtu1KBmTsjTP+AuIdKXfy8htiChLTuONePvZrZQtcU908Z9yqTgrGTnVDlNS7emrwipK6ntXuPTHlans6/eve+8++bB9K4dwIL+JaHE2AAcynWOJWdApGA0e/mxoEAsPmIDhrhFJjnX5ivqxlxgnZAEeNJdYrNaBvDUQEs3rcssJSJuWVKwYIe5CRf323KoqC6GfL1NW2HB8PuEkoWE6K510dozb9KhBxNvKVdkidctzkRl8l0EEmM+Hn4vQZkOLSY6GMvpmHYZV8L6AGGKBw489R/7eE1VZeytYJWx+xCUevmP5OLcaLDTaCWQt5ArkkEtCm/oEqPX1YmHFHsKTP0q0aP6pGcGZBWpEpBVkXklXavK1YLsdLIae2yZJFQozgvnAQkEqhrQTAQSjs3P8DyAfmnAY0uvahWlBC6rEd9HuIKyg6I1Sa45dLQ28r3PlKCqFUUpVPtoFZ7et2v++vXsfvuW/Xx7P/vw8OeDofdf/+3w+f7vh9tBsXlo0yjWP/n1ZzKD+W/ffT+DlXm4XZCXfyrijRYHC6s7vD11bGP79UeCt4Ah2YrL9XaxQeSw5/gSr5x1IH8AmdRQUIhPvK7fMxQpgRu7hj3221g7xb/pp/8FWu8MG68XAAA='
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force};[IO.File]::WriteAllText($p,$c,$Utf8)}
function Slots([string]$h){$m="<!-- CATALOGO-S:SLOT:MENU:START -->`r`n<!-- CATALOGO-S:SLOT:MENU:END -->";$c="<!-- CATALOGO-S:SLOT:COMPONENTES:START -->`r`n<!-- CATALOGO-S:SLOT:COMPONENTES:END -->";$f="<!-- CATALOGO-S:SLOT:RODAPE:START -->`r`n<!-- CATALOGO-S:SLOT:RODAPE:END -->";if($h-notmatch'CATALOGO-S:SLOT:MENU:START'){$h=$h-replace'(?i)<body([^>]*)>',('<body$1>'+"`r`n"+$m)};if($h-notmatch'CATALOGO-S:SLOT:COMPONENTES:START'){$h=$h-replace'(?i)</body>',($c+"`r`n</body>")};if($h-notmatch'CATALOGO-S:SLOT:RODAPE:START'){$h=$h-replace'(?i)</body>',($f+"`r`n</body>")};$h}
function SetSlot([string]$h,[string]$n,[string]$c){$e=[Text.RegularExpressions.Regex]::Escape($n);[Text.RegularExpressions.Regex]::Replace($h,'(?s)<!-- CATALOGO-S:SLOT:'+$e+':START -->.*?<!-- CATALOGO-S:SLOT:'+$e+':END -->',"<!-- CATALOGO-S:SLOT:$n`:START -->`r`n$c`r`n<!-- CATALOGO-S:SLOT:$n`:END -->")}
$p=Full 'index.html';if(!(Test-Path -LiteralPath $p)){Put 'index.html' (Slots '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Projeto</title></head><body></body></html>')};$h=Slots ([IO.File]::ReadAllText($p));Put 'components/catalogo-s/rodape/ativo.html' $ConteudoModelo;Put 'index.html' (SetSlot $h 'RODAPE' $ConteudoModelo)
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado como rodapé ativo."
Write-Host '[Catálogo S] Fxx é singleton: outro Fxx substitui somente o rodapé.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
