$ModeloId='F05'
$ModeloNome='Rodapé Utilitário de Aplicação'
$Payload='H4sIAAKKmWoC/5VWXW7jNhB+zykIGwvERRRLSvwTyjG63aJonzZocgFapGR2JVKgKNup4Wv0An0IeoK+9WFzk56kQ0p2JFlqUwRwRA458833zYy0iKTUTCFO7wch0SSRsXQidzJAFFbOaSt3UklZcj/4AWzLi0WunxO2vBjW7+wdZxXjYXQbTaN54DhcfMFDb+67PoFVWmhG8XA6nXlzF9YJFwwPacg8NoPlKilg6U+mN2wVrEj4JVayEBRviLo0fkdBKBOpqjW4HgWRFNqJSMqTZ/xRcZJc/ciSDdM8JFc5EbmTM8WjYCUVZcrRMsNetkO5TDhFpRuDYXRoZoG+2a/kzsn5r1zEuLoMO4fmKbIv8XCxhig60GynHcpCqYjmUmAhBWt7voYfZ6tItt9yqtc45eLSu/HdbHcVkiS89Fz3A3LQjZ/tRqMgJSrmApNCyyAjlBo4PpiQ2+lXye2e8jxLyDOOFaeB+XE0S2FHMwfQFqnIrTvkRQpZvyThsXA4nMpxyARUQhCTDPvzbBcAOmfNeLzWeAZhO4OuFBH0FDZK2K7PpQfcl4ptS593rluugWmGvRuI8OYS8Yoi/w6uVSjscyNFeApZM1YlmCKUFzk2edSK6ViNpXTDKIoqCKaaQTKVkqQOyu1JW5DNu5I20gbmgFUdm59Dt7tTPZWFaZtlVIfSpm/mur2u8FpumGo4NO016sxFS5nk78pm3sNGCLCUTK46THmRZVLpfaXgzbSm4H+EqpTs7tmWzHctmY2wx5ZxkeWukvx2MnEnrKVxg9i5291fx1T+vZwqXNVOae90lzJNmqz/UuSaR8+WTmAC55kp7hXTW8ZE2UOGliqvcp7NTjz1z7cjvBmbz+8mtdTvevTMNdHF+0piduza8s6pbWdvXVuDWKk1cT801PKjFZnSwE7dNaFyC5qZPxgJqDJ6814S0VkzWqom55138W3KKCeXKYFdCxO0hlG775mm3QP0ODt7uq+8VR7G3tjxyjkM/rB/0m4ltZapbagOVBO/D1Xt3VF/Yfi3cP7wf7M49A6DdiVaHkFhpd83zBoc2PfMiYNyZQQyA7+vL+rV1g5OuWKhfcWWAYDBxbj6HFlQvkFhQvL8fnDkC75WEGobAIrdP7fY189gueDLz4+LMV8uoA3F8rNacY0+SQHdxSCc2VuM4WrlxIzdmhNYgguC1opF94PhYPm9DIsUqCSvL6+/y8WYNKwfH35qb31aExEzoKZteLSNdnZcpoXglFBmLWMA0J2eFRiwtbarET5YPjw53/2M/v7trzK73nNPLCXo65/okeegEqlOk/rZamAOatgLs1FBrMh7e2iFMoVwDrScM1afN3Uemdrw1xeZI5kxRUIoDsJzA29zez2/9huCGa0a3D0ovoE7J/JqpiemUnlG9iOLC6iS1xdiLdb31z8QjPopsoVyimdDlQme/pUf3Mt/AG8Ja3N5CwAA'
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force};[IO.File]::WriteAllText($p,$c,$Utf8)}
function Slots([string]$h){$m="<!-- CATALOGO-S:SLOT:MENU:START -->`r`n<!-- CATALOGO-S:SLOT:MENU:END -->";$c="<!-- CATALOGO-S:SLOT:COMPONENTES:START -->`r`n<!-- CATALOGO-S:SLOT:COMPONENTES:END -->";$f="<!-- CATALOGO-S:SLOT:RODAPE:START -->`r`n<!-- CATALOGO-S:SLOT:RODAPE:END -->";if($h-notmatch'CATALOGO-S:SLOT:MENU:START'){$h=$h-replace'(?i)<body([^>]*)>',('<body$1>'+"`r`n"+$m)};if($h-notmatch'CATALOGO-S:SLOT:COMPONENTES:START'){$h=$h-replace'(?i)</body>',($c+"`r`n</body>")};if($h-notmatch'CATALOGO-S:SLOT:RODAPE:START'){$h=$h-replace'(?i)</body>',($f+"`r`n</body>")};$h}
function SetSlot([string]$h,[string]$n,[string]$c){$e=[Text.RegularExpressions.Regex]::Escape($n);[Text.RegularExpressions.Regex]::Replace($h,'(?s)<!-- CATALOGO-S:SLOT:'+$e+':START -->.*?<!-- CATALOGO-S:SLOT:'+$e+':END -->',"<!-- CATALOGO-S:SLOT:$n`:START -->`r`n$c`r`n<!-- CATALOGO-S:SLOT:$n`:END -->")}
$p=Full 'index.html';if(!(Test-Path -LiteralPath $p)){Put 'index.html' (Slots '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Projeto</title></head><body></body></html>')};$h=Slots ([IO.File]::ReadAllText($p));Put 'components/catalogo-s/rodape/ativo.html' $ConteudoModelo;Put 'index.html' (SetSlot $h 'RODAPE' $ConteudoModelo)
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado como rodapé ativo."
Write-Host '[Catálogo S] Fxx é singleton: outro Fxx substitui somente o rodapé.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
