$ModeloId='F01'
$ModeloNome='Rodapé Institucional Sólido'
$Payload='H4sIAAKKmWoC/51YTW/bOBC991cQDgrYu5EtyXbsSK7RYj/SAO2i2KSHHilxZLORRIGkEqeGf80eit37Yu/NH9uhPmzLtdzdBq0qcciZN4/zhkxnkRAaJOHsRSekmsZiIazIdjqE4Ze1HVJWIhjELzq/om3+bKb0YwzzZ2f7a9aWFSy8MzuwmeP4lpXRFGLvzHGcsRPgt4aV9s6iUeTAJX4muQbmnV0G1KUMv2OeApqLH2eKAzQMIcUV7DKYTC79gIZ3CynylHn3VHZNsJ4filjI6tv47/mRSLUV0YTHj94ryWl8/hrie9A8pOeKpspSIHm0aUInP6wDsbIU/8TThRcIyUBaOLJpzqLrMh5Pl+hE+yaixSAUkmouUi8VKRwu8ZbiHuR6H2iZWO8QQx8f1oOk2fqBM730Ep52HXdkZ6vzkMZh17Ht58QiZqDX8xMqFzz1aK6Fn1HGDPCLUbYiNnEvstVR5wnl6ZpxlcX00VtIznzzQOISHNFgIcg8SZWJnNBV1x2b2E5/OI5kj0jIgOru6LyyOq6x9ido6/kLmnkjN1vVUJA8rUXijRCKv+WzGHIQoxIxZ6Rkw+z7cS4CSVO2xlhWSchwiBE3Ryaar21eUQwrn8Z8kVocM1OeIRtkAdExEEvmtnCmOGSKxruwkTpkcOCQKxA4BwvG1Iofg0YHlspoaFi2+rYLSQvB8q7avaHJfAl8sdTle4N3fAuhia9kaY+eqvAvLmoCJWU8V55jG053ajAEUmktjBlddZ3RmMHivFruhOeVqOxpUy9VGZbJByJmxBli8EI0fiGHJWXiAatdgcayMshqfUbtG0aydVWbdiNcofdKnyg08Ew034C3Kpqc/mR81C+6Icth7dYtityZ4OrSvwG179cxfpt71nfGkJR61QhSRUImXp5lIEOqoDVoHq9jrtCvaXeFvP1tbrXo7ObO1mW2aXFZ95CzYBpAODnko0DHi25SzCN9VxFox5hqGupm7ZtH0Uc88zgmhY+50jx6LJabFmtYAisA/QCQlhlMd1r23ILx75ZxBZIoLUW6WO8l3EpTtQBPkPXpEnJbOp0SIVZxkxeT1/R4xHI67k2l3dGedkffo909Tg7UO7af12XLIhjCdD8du+pF1kMZ/NK29yviZC3UOVQHzq7MizfT3z90LeRrC6hGUbSJyeS4oovNbvL47eoxJ8P2JNACB0Y7sU7cyeV0fKDXE8FJSu9PFngdcfPsZQKM0+7uxED+MOF121F4/PRz+m4kiVP+3bSeS8Xico3nDCzH34UdmzN6cwTPhduG5/DcL896d2oO4OIO0GsQOhodL+RTaZUJFXQNjaLdFvkdT2/TXh3FfjAuIaz7Fi7C9GeD6po4Y/yehDFV6kWnThZvkYQcGgz8woAmVbrbNxfIKvvXiw22znxmukbTp7zrzG8QDBpK8/wmp+Qtxd5fjw7Q19ZvNn+fUMJAhZI/fX76Q5Awl5oSIJkUEVcKYaHSGI4kmQRFz42B4U2MiNy8fgQt+uS9AgJKm0dGnz4LklFJ8RqFonz6TCXJhOKhcZWgigR6R0FFnKZo7M8GWUXDoOKh+kQx7CeHXGPKy+H8lxLJbIDvszyez2I+n1GyxHAvOmeYvwgkzAYUUzWWA+tPVErgkqrWGdfGf2oCtLkwTVuLnX1gUAwQ7zeQvyupa0X+OyD7SpyAhm0ILz+4U39D+6x3EnAP2u2vdI4n5aev3PzXNG7yTEgNrWn8hJssTdUAoR9z1k7kzyLMTUXQovRap90g27k6sR1JnnJGGfz/VN7AgsatibyT/B4vVU3XB3NuQSbiFDhxx0/s1RuO5yrKoG0btnI9bAHVzQHTMBNm5Y0DtxZSxguVmZZUjJGyEYRl1b5UOa203A/xyPnyD/lxPCbdodMjNv5Y5tHoFYeRy9O3s58GoXiTtmIamN+br1OlKVZpgvV6VaTVMvENT++AXWMbvP7t1LwPIr/NA+jMP9yemnbF9es86MyvXpdcFtjb6Cv7edVD51/+JK7tXpBts+yTW8GEIvjHdHuu8QUpA3mPvyeofs2P2aSGskLAlhnweFczTV1GIJ/+SpE/dWh8SzNsxILg/acqtsJ5iX/7T/l/GPN/AS/uOO7MEAAA'
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force};[IO.File]::WriteAllText($p,$c,$Utf8)}
function Slots([string]$h){$m="<!-- CATALOGO-S:SLOT:MENU:START -->`r`n<!-- CATALOGO-S:SLOT:MENU:END -->";$c="<!-- CATALOGO-S:SLOT:COMPONENTES:START -->`r`n<!-- CATALOGO-S:SLOT:COMPONENTES:END -->";$f="<!-- CATALOGO-S:SLOT:RODAPE:START -->`r`n<!-- CATALOGO-S:SLOT:RODAPE:END -->";if($h-notmatch'CATALOGO-S:SLOT:MENU:START'){$h=$h-replace'(?i)<body([^>]*)>',('<body$1>'+"`r`n"+$m)};if($h-notmatch'CATALOGO-S:SLOT:COMPONENTES:START'){$h=$h-replace'(?i)</body>',($c+"`r`n</body>")};if($h-notmatch'CATALOGO-S:SLOT:RODAPE:START'){$h=$h-replace'(?i)</body>',($f+"`r`n</body>")};$h}
function SetSlot([string]$h,[string]$n,[string]$c){$e=[Text.RegularExpressions.Regex]::Escape($n);[Text.RegularExpressions.Regex]::Replace($h,'(?s)<!-- CATALOGO-S:SLOT:'+$e+':START -->.*?<!-- CATALOGO-S:SLOT:'+$e+':END -->',"<!-- CATALOGO-S:SLOT:$n`:START -->`r`n$c`r`n<!-- CATALOGO-S:SLOT:$n`:END -->")}
$p=Full 'index.html';if(!(Test-Path -LiteralPath $p)){Put 'index.html' (Slots '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Projeto</title></head><body></body></html>')};$h=Slots ([IO.File]::ReadAllText($p));Put 'components/catalogo-s/rodape/ativo.html' $ConteudoModelo;Put 'index.html' (SetSlot $h 'RODAPE' $ConteudoModelo)
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado como rodapé ativo."
Write-Host '[Catálogo S] Fxx é singleton: outro Fxx substitui somente o rodapé.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
