# Normaliza páginas que no catálogo são armazenadas como fragmentos visuais.
# CTxx já fornece um documento HTML completo para a página canônica contato.html.
$ModeloId='CT03'
$ModeloNome='Central de Contato por Intenção'
$Payload='H4sIAO6pmWoC/61YTY/juBG996/QehDYTiz5s91uyXZ2dtDJbpDDJDsJEAQ50BJls0cStSTlttfwdf9CzkEOQQ455pJr/5P8krwSJX+1e2ewCAbjD4pVrHr16rHc0y8iGZptzp2VSZP5zZTenIRly1kjN+5Xv284ETPMDfGSyKV0tZvKiCezxrsPvWFjPl1xFs2nKTfMCVdMaW5mjcLE7qRRrWYs5bPGWvCnXCrTcEKZGZ5h15OIzGoW8bUIuVt+6YhMGMESV4cs4bM+XBhhEj5/Bxtm5LRrv95MtdnS+893C7lxtfheZEt/IVXElYuVPSXRWchou0uZWorM7wULFn5cKllkkf8mHsY9PglCmUjlv+n3+0GMA9yYpSLZ+m8VQuh8zZM1NyJkHc0y7WquRBzINVdxIp/cjb8SUcSzvRea3nCXisxdcbFcGb/f6+n1KshZFFFQYcLSvDUc5ZvOeP3UmYzzTTuIhM4TtvWXSkQBPiF/YXiq/RDAcLX3nhTLdyUkPly3+v1JDw7g+mftvUeI785c0IsLB1gx3EVaRZppv+/1Y+V497EKliz3R3ARsEQss+ownkWBhQeYGSNTfzTIN9a/s+rvCBN/3Os5NofRBCHcUQ740O5690Pn11zCHAiV4NRQVx7yA/ZOz4FJDfft+HY0ii3iqBz3+3d4mIiMHyD07vYeSmW4/pw8Fc85M61RB+m2g4oFRuZ+P984WiYict70Gf0LDhQp033xvDp1x3J4VCwLuZ/JjFdmRCJrr2yYL90fOWZgrnOmUNDA8I1xS+T9hMfmwI0ByOAMgHlwyp97qlNYKA2wcimIEEEuNRpDZsgVqYs1D0r/ds0b3Ooqcj9h2rjhSiTR7izWXrXB8bIi3Z1gPzgW5u6uht3RRslseQB/kcjwY3DgwwBs7oJd1+tPPEPF+z3iUuUuZ9muOmU8GY/HvdPyD1+U/7ZOh8XIflcpht/47w9/bRyxYAugj11BVQ7iGJV9QAAe/Q8Gh0D8FTVwx37xWEhI7k6FgaSgijO+i0c8PDMs8zi3Pl2qNhHCF5tK0Cu/4SQcLMZ7D3Y8+aw2RhOzwsiyiYeXTWwV44xAt7TnwLEJVSOQOQuF2YLCJXFiqVJLUTrqTy2iQfuMU0NdhejplXza1fb9E3tqjWqTsxqckIr4EZw3f73vKAo1zuPb8fD24IcdEBFZyYk44VcTfiy0EfHWrblRLddpE6mckhF1G7BIFNq/v7+ntVdKHse2VyMeSsVKIMr+L1N7svBOer39zZcpjwRrpWxjLy5/QqC3d1abX63jQdVer/Rxl5+ZlW3l1qB9vZtPtrjZL467XtW3/YvAb0c28E8FVkvjeRxfiJQudQaR+zxpvSJQlUWvbolXQzijgTZMmf3+Ztq1o8C0awcRuvQxeDCR0bWl9axBFzQGiUis6xW6XRs06sACDVut0jeaZ/qYNlLp5JhyUqkd9lhETP0S/vvzaT5/SJ01/96JuPMol0w5RkbMSXmm2ZKnmHXwWacYhZjYMNoFWoJ6rONwREwvqjCFwiOheAiC0VZ4yLnWEm+4dRyJJfTzCu9cGenQ2OVkiEiJlAuF5UR8V3Bv2s2rtLmikYiHxNg6HVvQhsMwzbgJW9DI9kFAPCmq0M5TBMKiAPznVo6VrWryK0euWeNXLEG6oaT8s4jpei6U+RazoMwgfRpyKBeKOyhdJnUHEUscaBg+EpgZsmfP/3j+N9cOR0ZrBIMtj9xI7VX+0PQfZw3ULzHStyd9CS4orpmHw1EgUtw6XOhqY97rgwRYxKPy2pr/sTQjZpRfS4v57wpO0En4Qh6ycDBrhgIfi7QOwqv9dC0o19E5h+XbghoAkJVlIRE6A+YPwARFB+IsY4mtb/T8n7VAgI55/meIIJhFapHwlBEwjIJk2Qpzc4agrgGj7amfRGZwgUwV7QU0v3n+GwpX1AkghJzIqSVRpeT/T0HmPVPgr7hgyvuaEuSbhptlSYm/S3TImvIFGLhdMh7ySKqSKJAABq2omHMVj7w+65OIDC8QOUT5Cl2Is4XADZygCdHhWHkssp/GlW8oNigFckqf/wUdPkPmAUqB30K2XVJoH6ISGhjhojNFqRWC4CBZxV1cNxLBWPm9Ck398JPIjC6QqaO9AOZ9RY34oAf4XxCNyzJewaVbKdNLjbJ3Pg0YDUdEVqrdcrHWLcgQtiFjYFlqOAR6ML/UIqjggMT5/yBDVlTLg5izUjz+UTF6u1DgRtnb0y6bn6ZqfXTpJgJyoRK5md+UfHKsNM/+7HkefnwX1OYeBF1tv+UJ7KV6myStpr0wm+2/dEpEZoetS24eoBX4+NX2m6jVPKLWbAfWt4cWemDhqrUw2WyOFw9z0QP1129BMJ5xBTPQ6GOz02rP5rsLq81svvHKGtF2TwG0NW817bXQbONHFjwen8P38WFgp8aX1lRmPNbcfMA9hgNb5dF2+1n6reZq0Gx7NIq9q/5YQAcSt2Htld0UXLXLf8SMuuy6FYNVWerT7dREL3IpM7WJ7Dv9Qa+9BxjEcFtfkL4cP7rl31L+B1kiMHtbEQAA'
$ms=New-Object IO.MemoryStream(,[Convert]::FromBase64String($Payload))
$gz=New-Object IO.Compression.GzipStream($ms,[IO.Compression.CompressionMode]::Decompress)
$sr=New-Object IO.StreamReader($gz,[Text.Encoding]::UTF8)
$ConteudoModelo=$sr.ReadToEnd();$sr.Dispose();$gz.Dispose();$ms.Dispose()
$ErrorActionPreference='Stop'
$Root=(Get-Location).Path
$Utf8=New-Object System.Text.UTF8Encoding($false)
function Full([string]$r){[IO.Path]::GetFullPath((Join-Path $Root $r))}
function Backup([string]$r){$p=Full $r;if(!(Test-Path -LiteralPath $p)){return};$bd=Full '.catalogo-s/backups';New-Item -ItemType Directory -Force -Path $bd|Out-Null;$safe=$r-replace'[\/:*?"<>|]','__';Copy-Item -LiteralPath $p -Destination (Join-Path $bd ((Get-Date -Format 'yyyyMMdd-HHmmssfff')+'__'+$safe+'.bak')) -Force}
function Put([string]$r,[string]$c){$p=Full $r;$d=Split-Path -Parent $p;if($d-and!(Test-Path -LiteralPath $d)){New-Item -ItemType Directory -Force -Path $d|Out-Null};if(Test-Path -LiteralPath $p){$old=[IO.File]::ReadAllText($p);if($old-eq$c){return};Backup $r};[IO.File]::WriteAllText($p,$c,$Utf8)}
if($env:CATALOGO_S_CONTACT_EMAIL){$e=$env:CATALOGO_S_CONTACT_EMAIL.Trim();if($e){$ConteudoModelo=[Text.RegularExpressions.Regex]::Replace($ConteudoModelo,'[A-Za-z]+@empresa\.com',[Text.RegularExpressions.MatchEvaluator]{param($m)$e})}}
if($env:CATALOGO_S_CONTACT_ENDPOINT){$e=$env:CATALOGO_S_CONTACT_ENDPOINT.Trim();if($e){$s=[System.Net.WebUtility]::HtmlEncode($e);$ConteudoModelo=$ConteudoModelo.Replace('data-contact-endpoint=""','data-contact-endpoint="'+$s+'"')}}
if($env:CATALOGO_S_WHATSAPP){$ConteudoModelo=$ConteudoModelo.Replace('https://wa.me/5500000000000',$env:CATALOGO_S_WHATSAPP.Trim())}
if($env:CATALOGO_S_INSTAGRAM){$ConteudoModelo=$ConteudoModelo.Replace('https://instagram.com/',$env:CATALOGO_S_INSTAGRAM.Trim())}
if($env:CATALOGO_S_FACEBOOK){$ConteudoModelo=$ConteudoModelo.Replace('https://facebook.com/',$env:CATALOGO_S_FACEBOOK.Trim())}
Put 'contato.html' $ConteudoModelo
Write-Host "[Catálogo S] $ModeloId — $ModeloNome instalado em contato.html."
Write-Host '[Catálogo S] CTxx substitui somente contato.html e cria backup quando necessário.'
Write-Host '[Catálogo S] Nenhum arquivo foi baixado do GitHub.'
